/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.qa.service.model.impl;

import com.ecoit.qa.service.model.GroupUserUser;
import com.ecoit.qa.service.model.GroupUserUserModel;
import com.ecoit.qa.service.model.GroupUserUserSoap;
import com.ecoit.qa.service.service.persistence.GroupUserUserPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GroupUserUser service. Represents a row in the &quot;ecoit_qa_GroupUserUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GroupUserUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GroupUserUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GroupUserUserImpl
 * @generated
 */
@JSON(strict = true)
public class GroupUserUserModelImpl
	extends BaseModelImpl<GroupUserUser> implements GroupUserUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a group user user model instance should use the <code>GroupUserUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_qa_GroupUserUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"groupUserId", Types.BIGINT}, {"userId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("groupUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_qa_GroupUserUser (groupUserId LONG not null,userId LONG not null,primary key (groupUserId, userId))";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_qa_GroupUserUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY groupUserUser.id.groupUserId ASC, groupUserUser.id.userId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_qa_GroupUserUser.groupUserId ASC, ecoit_qa_GroupUserUser.userId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GROUPUSERID_COLUMN_BITMASK = 1L;

	public static final long USERID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GroupUserUser toModel(GroupUserUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GroupUserUser model = new GroupUserUserImpl();

		model.setGroupUserId(soapModel.getGroupUserId());
		model.setUserId(soapModel.getUserId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GroupUserUser> toModels(GroupUserUserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<GroupUserUser> models = new ArrayList<GroupUserUser>(
			soapModels.length);

		for (GroupUserUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GroupUserUserModelImpl() {
	}

	@Override
	public GroupUserUserPK getPrimaryKey() {
		return new GroupUserUserPK(_groupUserId, _userId);
	}

	@Override
	public void setPrimaryKey(GroupUserUserPK primaryKey) {
		setGroupUserId(primaryKey.groupUserId);
		setUserId(primaryKey.userId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new GroupUserUserPK(_groupUserId, _userId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((GroupUserUserPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return GroupUserUser.class;
	}

	@Override
	public String getModelClassName() {
		return GroupUserUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GroupUserUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GroupUserUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GroupUserUser)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GroupUserUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GroupUserUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GroupUserUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GroupUserUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GroupUserUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GroupUserUser>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GroupUserUser.class.getClassLoader(), GroupUserUser.class,
			ModelWrapper.class);

		try {
			Constructor<GroupUserUser> constructor =
				(Constructor<GroupUserUser>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GroupUserUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GroupUserUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GroupUserUser, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GroupUserUser, Object>>();
		Map<String, BiConsumer<GroupUserUser, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GroupUserUser, ?>>();

		attributeGetterFunctions.put(
			"groupUserId", GroupUserUser::getGroupUserId);
		attributeSetterBiConsumers.put(
			"groupUserId",
			(BiConsumer<GroupUserUser, Long>)GroupUserUser::setGroupUserId);
		attributeGetterFunctions.put("userId", GroupUserUser::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<GroupUserUser, Long>)GroupUserUser::setUserId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getGroupUserId() {
		return _groupUserId;
	}

	@Override
	public void setGroupUserId(long groupUserId) {
		_columnBitmask |= GROUPUSERID_COLUMN_BITMASK;

		if (!_setOriginalGroupUserId) {
			_setOriginalGroupUserId = true;

			_originalGroupUserId = _groupUserId;
		}

		_groupUserId = groupUserId;
	}

	@Override
	public String getGroupUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getGroupUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setGroupUserUuid(String groupUserUuid) {
	}

	public long getOriginalGroupUserId() {
		return _originalGroupUserId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public GroupUserUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GroupUserUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GroupUserUserImpl groupUserUserImpl = new GroupUserUserImpl();

		groupUserUserImpl.setGroupUserId(getGroupUserId());
		groupUserUserImpl.setUserId(getUserId());

		groupUserUserImpl.resetOriginalValues();

		return groupUserUserImpl;
	}

	@Override
	public int compareTo(GroupUserUser groupUserUser) {
		GroupUserUserPK primaryKey = groupUserUser.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GroupUserUser)) {
			return false;
		}

		GroupUserUser groupUserUser = (GroupUserUser)obj;

		GroupUserUserPK primaryKey = groupUserUser.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GroupUserUserModelImpl groupUserUserModelImpl = this;

		groupUserUserModelImpl._originalGroupUserId =
			groupUserUserModelImpl._groupUserId;

		groupUserUserModelImpl._setOriginalGroupUserId = false;

		groupUserUserModelImpl._originalUserId = groupUserUserModelImpl._userId;

		groupUserUserModelImpl._setOriginalUserId = false;

		groupUserUserModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GroupUserUser> toCacheModel() {
		GroupUserUserCacheModel groupUserUserCacheModel =
			new GroupUserUserCacheModel();

		groupUserUserCacheModel.groupUserUserPK = getPrimaryKey();

		groupUserUserCacheModel.groupUserId = getGroupUserId();

		groupUserUserCacheModel.userId = getUserId();

		return groupUserUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GroupUserUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GroupUserUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GroupUserUser)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GroupUserUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GroupUserUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GroupUserUser)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GroupUserUser>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _groupUserId;
	private long _originalGroupUserId;
	private boolean _setOriginalGroupUserId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _columnBitmask;
	private GroupUserUser _escapedModel;

}