/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.qa.service.model.impl;

import com.ecoit.qa.service.model.GroupUserCategory;
import com.ecoit.qa.service.model.GroupUserCategoryModel;
import com.ecoit.qa.service.model.GroupUserCategorySoap;
import com.ecoit.qa.service.service.persistence.GroupUserCategoryPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GroupUserCategory service. Represents a row in the &quot;ecoit_qa_GroupUserCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GroupUserCategoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GroupUserCategoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GroupUserCategoryImpl
 * @generated
 */
@JSON(strict = true)
public class GroupUserCategoryModelImpl
	extends BaseModelImpl<GroupUserCategory> implements GroupUserCategoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a group user category model instance should use the <code>GroupUserCategory</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_qa_GroupUserCategory";

	public static final Object[][] TABLE_COLUMNS = {
		{"groupUserId", Types.BIGINT}, {"categoryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("groupUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_qa_GroupUserCategory (groupUserId LONG not null,categoryId LONG not null,primary key (groupUserId, categoryId))";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_qa_GroupUserCategory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY groupUserCategory.id.groupUserId ASC, groupUserCategory.id.categoryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_qa_GroupUserCategory.groupUserId ASC, ecoit_qa_GroupUserCategory.categoryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CATEGORYID_COLUMN_BITMASK = 1L;

	public static final long GROUPUSERID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GroupUserCategory toModel(GroupUserCategorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GroupUserCategory model = new GroupUserCategoryImpl();

		model.setGroupUserId(soapModel.getGroupUserId());
		model.setCategoryId(soapModel.getCategoryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GroupUserCategory> toModels(
		GroupUserCategorySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<GroupUserCategory> models = new ArrayList<GroupUserCategory>(
			soapModels.length);

		for (GroupUserCategorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GroupUserCategoryModelImpl() {
	}

	@Override
	public GroupUserCategoryPK getPrimaryKey() {
		return new GroupUserCategoryPK(_groupUserId, _categoryId);
	}

	@Override
	public void setPrimaryKey(GroupUserCategoryPK primaryKey) {
		setGroupUserId(primaryKey.groupUserId);
		setCategoryId(primaryKey.categoryId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new GroupUserCategoryPK(_groupUserId, _categoryId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((GroupUserCategoryPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return GroupUserCategory.class;
	}

	@Override
	public String getModelClassName() {
		return GroupUserCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GroupUserCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GroupUserCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserCategory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GroupUserCategory)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GroupUserCategory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GroupUserCategory, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GroupUserCategory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GroupUserCategory, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GroupUserCategory, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GroupUserCategory>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GroupUserCategory.class.getClassLoader(), GroupUserCategory.class,
			ModelWrapper.class);

		try {
			Constructor<GroupUserCategory> constructor =
				(Constructor<GroupUserCategory>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GroupUserCategory, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GroupUserCategory, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GroupUserCategory, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<GroupUserCategory, Object>>();
		Map<String, BiConsumer<GroupUserCategory, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<GroupUserCategory, ?>>();

		attributeGetterFunctions.put(
			"groupUserId", GroupUserCategory::getGroupUserId);
		attributeSetterBiConsumers.put(
			"groupUserId",
			(BiConsumer<GroupUserCategory, Long>)
				GroupUserCategory::setGroupUserId);
		attributeGetterFunctions.put(
			"categoryId", GroupUserCategory::getCategoryId);
		attributeSetterBiConsumers.put(
			"categoryId",
			(BiConsumer<GroupUserCategory, Long>)
				GroupUserCategory::setCategoryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getGroupUserId() {
		return _groupUserId;
	}

	@Override
	public void setGroupUserId(long groupUserId) {
		_columnBitmask |= GROUPUSERID_COLUMN_BITMASK;

		if (!_setOriginalGroupUserId) {
			_setOriginalGroupUserId = true;

			_originalGroupUserId = _groupUserId;
		}

		_groupUserId = groupUserId;
	}

	@Override
	public String getGroupUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getGroupUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setGroupUserUuid(String groupUserUuid) {
	}

	public long getOriginalGroupUserId() {
		return _originalGroupUserId;
	}

	@JSON
	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		_columnBitmask |= CATEGORYID_COLUMN_BITMASK;

		if (!_setOriginalCategoryId) {
			_setOriginalCategoryId = true;

			_originalCategoryId = _categoryId;
		}

		_categoryId = categoryId;
	}

	public long getOriginalCategoryId() {
		return _originalCategoryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public GroupUserCategory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GroupUserCategory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GroupUserCategoryImpl groupUserCategoryImpl =
			new GroupUserCategoryImpl();

		groupUserCategoryImpl.setGroupUserId(getGroupUserId());
		groupUserCategoryImpl.setCategoryId(getCategoryId());

		groupUserCategoryImpl.resetOriginalValues();

		return groupUserCategoryImpl;
	}

	@Override
	public int compareTo(GroupUserCategory groupUserCategory) {
		GroupUserCategoryPK primaryKey = groupUserCategory.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GroupUserCategory)) {
			return false;
		}

		GroupUserCategory groupUserCategory = (GroupUserCategory)obj;

		GroupUserCategoryPK primaryKey = groupUserCategory.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GroupUserCategoryModelImpl groupUserCategoryModelImpl = this;

		groupUserCategoryModelImpl._originalGroupUserId =
			groupUserCategoryModelImpl._groupUserId;

		groupUserCategoryModelImpl._setOriginalGroupUserId = false;

		groupUserCategoryModelImpl._originalCategoryId =
			groupUserCategoryModelImpl._categoryId;

		groupUserCategoryModelImpl._setOriginalCategoryId = false;

		groupUserCategoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GroupUserCategory> toCacheModel() {
		GroupUserCategoryCacheModel groupUserCategoryCacheModel =
			new GroupUserCategoryCacheModel();

		groupUserCategoryCacheModel.groupUserCategoryPK = getPrimaryKey();

		groupUserCategoryCacheModel.groupUserId = getGroupUserId();

		groupUserCategoryCacheModel.categoryId = getCategoryId();

		return groupUserCategoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GroupUserCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GroupUserCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GroupUserCategory)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GroupUserCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GroupUserCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GroupUserCategory)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GroupUserCategory>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _groupUserId;
	private long _originalGroupUserId;
	private boolean _setOriginalGroupUserId;
	private long _categoryId;
	private long _originalCategoryId;
	private boolean _setOriginalCategoryId;
	private long _columnBitmask;
	private GroupUserCategory _escapedModel;

}