/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.software.cms.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.software.cms.model.GroupUserUsers;
import com.software.cms.model.GroupUserUsersModel;
import com.software.cms.model.GroupUserUsersSoap;
import com.software.cms.service.persistence.GroupUserUsersPK;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GroupUserUsers service. Represents a row in the &quot;soft_cms_GroupUserUsers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GroupUserUsersModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GroupUserUsersImpl}.
 * </p>
 *
 * @author DungNV
 * @see GroupUserUsersImpl
 * @generated
 */
@JSON(strict = true)
public class GroupUserUsersModelImpl
	extends BaseModelImpl<GroupUserUsers> implements GroupUserUsersModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a group user users model instance should use the <code>GroupUserUsers</code> interface instead.
	 */
	public static final String TABLE_NAME = "soft_cms_GroupUserUsers";

	public static final Object[][] TABLE_COLUMNS = {
		{"groupUserId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"groupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("groupUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table soft_cms_GroupUserUsers (groupUserId LONG not null,userId LONG not null,groupId LONG,primary key (groupUserId, userId))";

	public static final String TABLE_SQL_DROP =
		"drop table soft_cms_GroupUserUsers";

	public static final String ORDER_BY_JPQL =
		" ORDER BY groupUserUsers.id.groupUserId ASC, groupUserUsers.id.userId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY soft_cms_GroupUserUsers.groupUserId ASC, soft_cms_GroupUserUsers.userId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GROUPID_COLUMN_BITMASK = 1L;

	public static final long GROUPUSERID_COLUMN_BITMASK = 2L;

	public static final long USERID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GroupUserUsers toModel(GroupUserUsersSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GroupUserUsers model = new GroupUserUsersImpl();

		model.setGroupUserId(soapModel.getGroupUserId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GroupUserUsers> toModels(
		GroupUserUsersSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<GroupUserUsers> models = new ArrayList<GroupUserUsers>(
			soapModels.length);

		for (GroupUserUsersSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GroupUserUsersModelImpl() {
	}

	@Override
	public GroupUserUsersPK getPrimaryKey() {
		return new GroupUserUsersPK(_groupUserId, _userId);
	}

	@Override
	public void setPrimaryKey(GroupUserUsersPK primaryKey) {
		setGroupUserId(primaryKey.groupUserId);
		setUserId(primaryKey.userId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new GroupUserUsersPK(_groupUserId, _userId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((GroupUserUsersPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return GroupUserUsers.class;
	}

	@Override
	public String getModelClassName() {
		return GroupUserUsers.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GroupUserUsers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GroupUserUsers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserUsers, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GroupUserUsers)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GroupUserUsers, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GroupUserUsers, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GroupUserUsers)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GroupUserUsers, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GroupUserUsers, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GroupUserUsers>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GroupUserUsers.class.getClassLoader(), GroupUserUsers.class,
			ModelWrapper.class);

		try {
			Constructor<GroupUserUsers> constructor =
				(Constructor<GroupUserUsers>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GroupUserUsers, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GroupUserUsers, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GroupUserUsers, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GroupUserUsers, Object>>();
		Map<String, BiConsumer<GroupUserUsers, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GroupUserUsers, ?>>();

		attributeGetterFunctions.put(
			"groupUserId", GroupUserUsers::getGroupUserId);
		attributeSetterBiConsumers.put(
			"groupUserId",
			(BiConsumer<GroupUserUsers, Long>)GroupUserUsers::setGroupUserId);
		attributeGetterFunctions.put("userId", GroupUserUsers::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<GroupUserUsers, Long>)GroupUserUsers::setUserId);
		attributeGetterFunctions.put("groupId", GroupUserUsers::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<GroupUserUsers, Long>)GroupUserUsers::setGroupId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getGroupUserId() {
		return _groupUserId;
	}

	@Override
	public void setGroupUserId(long groupUserId) {
		_columnBitmask |= GROUPUSERID_COLUMN_BITMASK;

		if (!_setOriginalGroupUserId) {
			_setOriginalGroupUserId = true;

			_originalGroupUserId = _groupUserId;
		}

		_groupUserId = groupUserId;
	}

	@Override
	public String getGroupUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getGroupUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setGroupUserUuid(String groupUserUuid) {
	}

	public long getOriginalGroupUserId() {
		return _originalGroupUserId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public GroupUserUsers toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GroupUserUsers>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GroupUserUsersImpl groupUserUsersImpl = new GroupUserUsersImpl();

		groupUserUsersImpl.setGroupUserId(getGroupUserId());
		groupUserUsersImpl.setUserId(getUserId());
		groupUserUsersImpl.setGroupId(getGroupId());

		groupUserUsersImpl.resetOriginalValues();

		return groupUserUsersImpl;
	}

	@Override
	public int compareTo(GroupUserUsers groupUserUsers) {
		GroupUserUsersPK primaryKey = groupUserUsers.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GroupUserUsers)) {
			return false;
		}

		GroupUserUsers groupUserUsers = (GroupUserUsers)obj;

		GroupUserUsersPK primaryKey = groupUserUsers.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GroupUserUsersModelImpl groupUserUsersModelImpl = this;

		groupUserUsersModelImpl._originalGroupUserId =
			groupUserUsersModelImpl._groupUserId;

		groupUserUsersModelImpl._setOriginalGroupUserId = false;

		groupUserUsersModelImpl._originalUserId =
			groupUserUsersModelImpl._userId;

		groupUserUsersModelImpl._setOriginalUserId = false;

		groupUserUsersModelImpl._originalGroupId =
			groupUserUsersModelImpl._groupId;

		groupUserUsersModelImpl._setOriginalGroupId = false;

		groupUserUsersModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GroupUserUsers> toCacheModel() {
		GroupUserUsersCacheModel groupUserUsersCacheModel =
			new GroupUserUsersCacheModel();

		groupUserUsersCacheModel.groupUserUsersPK = getPrimaryKey();

		groupUserUsersCacheModel.groupUserId = getGroupUserId();

		groupUserUsersCacheModel.userId = getUserId();

		groupUserUsersCacheModel.groupId = getGroupId();

		return groupUserUsersCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GroupUserUsers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GroupUserUsers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserUsers, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GroupUserUsers)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GroupUserUsers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GroupUserUsers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupUserUsers, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GroupUserUsers)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GroupUserUsers>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _groupUserId;
	private long _originalGroupUserId;
	private boolean _setOriginalGroupUserId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _columnBitmask;
	private GroupUserUsers _escapedModel;

}