/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.mr.service.base;

import com.ecoit.mr.model.MemberReport;
import com.ecoit.mr.service.MemberReportLocalService;
import com.ecoit.mr.service.persistence.MemberReportPersistence;
import com.ecoit.mr.service.persistence.PermissionGroupPersistence;
import com.ecoit.mr.service.persistence.UnitPersistence;
import com.ecoit.mr.service.persistence.UserGroupPersistence;
import com.ecoit.mr.service.persistence.UserPermissionGroupPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the member report local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ecoit.mr.service.impl.MemberReportLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.ecoit.mr.service.impl.MemberReportLocalServiceImpl
 * @generated
 */
public abstract class MemberReportLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, MemberReportLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MemberReportLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.ecoit.mr.service.MemberReportLocalServiceUtil</code>.
	 */

	/**
	 * Adds the member report to the database. Also notifies the appropriate model listeners.
	 *
	 * @param memberReport the member report
	 * @return the member report that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MemberReport addMemberReport(MemberReport memberReport) {
		memberReport.setNew(true);

		return memberReportPersistence.update(memberReport);
	}

	/**
	 * Creates a new member report with the primary key. Does not add the member report to the database.
	 *
	 * @param memberReportId the primary key for the new member report
	 * @return the new member report
	 */
	@Override
	@Transactional(enabled = false)
	public MemberReport createMemberReport(long memberReportId) {
		return memberReportPersistence.create(memberReportId);
	}

	/**
	 * Deletes the member report with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param memberReportId the primary key of the member report
	 * @return the member report that was removed
	 * @throws PortalException if a member report with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MemberReport deleteMemberReport(long memberReportId)
		throws PortalException {

		return memberReportPersistence.remove(memberReportId);
	}

	/**
	 * Deletes the member report from the database. Also notifies the appropriate model listeners.
	 *
	 * @param memberReport the member report
	 * @return the member report that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MemberReport deleteMemberReport(MemberReport memberReport) {
		return memberReportPersistence.remove(memberReport);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			MemberReport.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return memberReportPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.ecoit.mr.model.impl.MemberReportModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return memberReportPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.ecoit.mr.model.impl.MemberReportModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return memberReportPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return memberReportPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return memberReportPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public MemberReport fetchMemberReport(long memberReportId) {
		return memberReportPersistence.fetchByPrimaryKey(memberReportId);
	}

	/**
	 * Returns the member report matching the UUID and group.
	 *
	 * @param uuid the member report's UUID
	 * @param groupId the primary key of the group
	 * @return the matching member report, or <code>null</code> if a matching member report could not be found
	 */
	@Override
	public MemberReport fetchMemberReportByUuidAndGroupId(
		String uuid, long groupId) {

		return memberReportPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the member report with the primary key.
	 *
	 * @param memberReportId the primary key of the member report
	 * @return the member report
	 * @throws PortalException if a member report with the primary key could not be found
	 */
	@Override
	public MemberReport getMemberReport(long memberReportId)
		throws PortalException {

		return memberReportPersistence.findByPrimaryKey(memberReportId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(memberReportLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MemberReport.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("memberReportId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			memberReportLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MemberReport.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"memberReportId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(memberReportLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MemberReport.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("memberReportId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<MemberReport>() {

				@Override
				public void performAction(MemberReport memberReport)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, memberReport);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(MemberReport.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return memberReportLocalService.deleteMemberReport(
			(MemberReport)persistedModel);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return memberReportPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the member reports matching the UUID and company.
	 *
	 * @param uuid the UUID of the member reports
	 * @param companyId the primary key of the company
	 * @return the matching member reports, or an empty list if no matches were found
	 */
	@Override
	public List<MemberReport> getMemberReportsByUuidAndCompanyId(
		String uuid, long companyId) {

		return memberReportPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of member reports matching the UUID and company.
	 *
	 * @param uuid the UUID of the member reports
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of member reports
	 * @param end the upper bound of the range of member reports (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching member reports, or an empty list if no matches were found
	 */
	@Override
	public List<MemberReport> getMemberReportsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<MemberReport> orderByComparator) {

		return memberReportPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the member report matching the UUID and group.
	 *
	 * @param uuid the member report's UUID
	 * @param groupId the primary key of the group
	 * @return the matching member report
	 * @throws PortalException if a matching member report could not be found
	 */
	@Override
	public MemberReport getMemberReportByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return memberReportPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the member reports.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.ecoit.mr.model.impl.MemberReportModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of member reports
	 * @param end the upper bound of the range of member reports (not inclusive)
	 * @return the range of member reports
	 */
	@Override
	public List<MemberReport> getMemberReports(int start, int end) {
		return memberReportPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of member reports.
	 *
	 * @return the number of member reports
	 */
	@Override
	public int getMemberReportsCount() {
		return memberReportPersistence.countAll();
	}

	/**
	 * Updates the member report in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param memberReport the member report
	 * @return the member report that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MemberReport updateMemberReport(MemberReport memberReport) {
		return memberReportPersistence.update(memberReport);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MemberReportLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		memberReportLocalService = (MemberReportLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MemberReportLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MemberReport.class;
	}

	protected String getModelClassName() {
		return MemberReport.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = memberReportPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected MemberReportLocalService memberReportLocalService;

	@Reference
	protected MemberReportPersistence memberReportPersistence;

	@Reference
	protected PermissionGroupPersistence permissionGroupPersistence;

	@Reference
	protected UnitPersistence unitPersistence;

	@Reference
	protected UserGroupPersistence userGroupPersistence;

	@Reference
	protected UserPermissionGroupPersistence userPermissionGroupPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}