/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.lichcongtac.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LichCongTac service. Represents a row in the &quot;ecoit_lich_LichCongTac&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ecoit.lichcongtac.services.model.impl.LichCongTacModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ecoit.lichcongtac.services.model.impl.LichCongTacImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LichCongTac
 * @generated
 */
@ProviderType
public interface LichCongTacModel
	extends BaseModel<LichCongTac>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lich cong tac model instance should use the {@link LichCongTac} interface instead.
	 */

	/**
	 * Returns the primary key of this lich cong tac.
	 *
	 * @return the primary key of this lich cong tac
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lich cong tac.
	 *
	 * @param primaryKey the primary key of this lich cong tac
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lich cong tac ID of this lich cong tac.
	 *
	 * @return the lich cong tac ID of this lich cong tac
	 */
	public long getLichCongTacId();

	/**
	 * Sets the lich cong tac ID of this lich cong tac.
	 *
	 * @param lichCongTacId the lich cong tac ID of this lich cong tac
	 */
	public void setLichCongTacId(long lichCongTacId);

	/**
	 * Returns the group ID of this lich cong tac.
	 *
	 * @return the group ID of this lich cong tac
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lich cong tac.
	 *
	 * @param groupId the group ID of this lich cong tac
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the language of this lich cong tac.
	 *
	 * @return the language of this lich cong tac
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this lich cong tac.
	 *
	 * @param language the language of this lich cong tac
	 */
	public void setLanguage(String language);

	/**
	 * Returns the company ID of this lich cong tac.
	 *
	 * @return the company ID of this lich cong tac
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lich cong tac.
	 *
	 * @param companyId the company ID of this lich cong tac
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this lich cong tac.
	 *
	 * @return the user ID of this lich cong tac
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lich cong tac.
	 *
	 * @param userId the user ID of this lich cong tac
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lich cong tac.
	 *
	 * @return the user uuid of this lich cong tac
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lich cong tac.
	 *
	 * @param userUuid the user uuid of this lich cong tac
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lich cong tac.
	 *
	 * @return the user name of this lich cong tac
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lich cong tac.
	 *
	 * @param userName the user name of this lich cong tac
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lich cong tac.
	 *
	 * @return the create date of this lich cong tac
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lich cong tac.
	 *
	 * @param createDate the create date of this lich cong tac
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by user of this lich cong tac.
	 *
	 * @return the created by user of this lich cong tac
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this lich cong tac.
	 *
	 * @param createdByUser the created by user of this lich cong tac
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Returns the modified date of this lich cong tac.
	 *
	 * @return the modified date of this lich cong tac
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lich cong tac.
	 *
	 * @param modifiedDate the modified date of this lich cong tac
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by user of this lich cong tac.
	 *
	 * @return the modified by user of this lich cong tac
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this lich cong tac.
	 *
	 * @param modifiedByUser the modified by user of this lich cong tac
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Returns the ten lich of this lich cong tac.
	 *
	 * @return the ten lich of this lich cong tac
	 */
	@AutoEscape
	public String getTenLich();

	/**
	 * Sets the ten lich of this lich cong tac.
	 *
	 * @param tenLich the ten lich of this lich cong tac
	 */
	public void setTenLich(String tenLich);

	/**
	 * Returns the ngay bat dau of this lich cong tac.
	 *
	 * @return the ngay bat dau of this lich cong tac
	 */
	public Date getNgayBatDau();

	/**
	 * Sets the ngay bat dau of this lich cong tac.
	 *
	 * @param ngayBatDau the ngay bat dau of this lich cong tac
	 */
	public void setNgayBatDau(Date ngayBatDau);

	/**
	 * Returns the ngay ket thuc of this lich cong tac.
	 *
	 * @return the ngay ket thuc of this lich cong tac
	 */
	public Date getNgayKetThuc();

	/**
	 * Sets the ngay ket thuc of this lich cong tac.
	 *
	 * @param ngayKetThuc the ngay ket thuc of this lich cong tac
	 */
	public void setNgayKetThuc(Date ngayKetThuc);

	/**
	 * Returns the lich chuyen ban nganh of this lich cong tac.
	 *
	 * @return the lich chuyen ban nganh of this lich cong tac
	 */
	@AutoEscape
	public String getLichChuyenBanNganh();

	/**
	 * Sets the lich chuyen ban nganh of this lich cong tac.
	 *
	 * @param lichChuyenBanNganh the lich chuyen ban nganh of this lich cong tac
	 */
	public void setLichChuyenBanNganh(String lichChuyenBanNganh);

	/**
	 * Returns the lich chuyen nguoi dung of this lich cong tac.
	 *
	 * @return the lich chuyen nguoi dung of this lich cong tac
	 */
	@AutoEscape
	public String getLichChuyenNguoiDung();

	/**
	 * Sets the lich chuyen nguoi dung of this lich cong tac.
	 *
	 * @param lichChuyenNguoiDung the lich chuyen nguoi dung of this lich cong tac
	 */
	public void setLichChuyenNguoiDung(String lichChuyenNguoiDung);

	/**
	 * Returns the trangthai lich cong tac of this lich cong tac.
	 *
	 * @return the trangthai lich cong tac of this lich cong tac
	 */
	public int getTrangthaiLichCongTac();

	/**
	 * Sets the trangthai lich cong tac of this lich cong tac.
	 *
	 * @param trangthaiLichCongTac the trangthai lich cong tac of this lich cong tac
	 */
	public void setTrangthaiLichCongTac(int trangthaiLichCongTac);

	/**
	 * Returns the organization ID of this lich cong tac.
	 *
	 * @return the organization ID of this lich cong tac
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this lich cong tac.
	 *
	 * @param organizationId the organization ID of this lich cong tac
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the lydo tra ve of this lich cong tac.
	 *
	 * @return the lydo tra ve of this lich cong tac
	 */
	@AutoEscape
	public String getLydoTraVe();

	/**
	 * Sets the lydo tra ve of this lich cong tac.
	 *
	 * @param lydoTraVe the lydo tra ve of this lich cong tac
	 */
	public void setLydoTraVe(String lydoTraVe);

}