/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LegalAttachedMessage service. Represents a row in the &quot;ecoit_doc_LegalAttachedMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ecoit.elegaldocument.model.impl.LegalAttachedMessageModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ecoit.elegaldocument.model.impl.LegalAttachedMessageImpl</code>.
 * </p>
 *
 * @author Liverpool
 * @see LegalAttachedMessage
 * @generated
 */
@ProviderType
public interface LegalAttachedMessageModel
	extends BaseModel<LegalAttachedMessage>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal attached message model instance should use the {@link LegalAttachedMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this legal attached message.
	 *
	 * @return the primary key of this legal attached message
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this legal attached message.
	 *
	 * @param primaryKey the primary key of this legal attached message
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the message ID of this legal attached message.
	 *
	 * @return the message ID of this legal attached message
	 */
	@AutoEscape
	public String getMessageId();

	/**
	 * Sets the message ID of this legal attached message.
	 *
	 * @param messageId the message ID of this legal attached message
	 */
	public void setMessageId(String messageId);

	/**
	 * Returns the group ID of this legal attached message.
	 *
	 * @return the group ID of this legal attached message
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this legal attached message.
	 *
	 * @param groupId the group ID of this legal attached message
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this legal attached message.
	 *
	 * @return the company ID of this legal attached message
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this legal attached message.
	 *
	 * @param companyId the company ID of this legal attached message
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created date of this legal attached message.
	 *
	 * @return the created date of this legal attached message
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this legal attached message.
	 *
	 * @param createdDate the created date of this legal attached message
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by user of this legal attached message.
	 *
	 * @return the created by user of this legal attached message
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this legal attached message.
	 *
	 * @param createdByUser the created by user of this legal attached message
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Returns the article ID of this legal attached message.
	 *
	 * @return the article ID of this legal attached message
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article ID of this legal attached message.
	 *
	 * @param articleId the article ID of this legal attached message
	 */
	public void setArticleId(String articleId);

	/**
	 * Returns the content of this legal attached message.
	 *
	 * @return the content of this legal attached message
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this legal attached message.
	 *
	 * @param content the content of this legal attached message
	 */
	public void setContent(String content);

	/**
	 * Returns the read message of this legal attached message.
	 *
	 * @return the read message of this legal attached message
	 */
	public boolean getReadMessage();

	/**
	 * Returns <code>true</code> if this legal attached message is read message.
	 *
	 * @return <code>true</code> if this legal attached message is read message; <code>false</code> otherwise
	 */
	public boolean isReadMessage();

	/**
	 * Sets whether this legal attached message is read message.
	 *
	 * @param readMessage the read message of this legal attached message
	 */
	public void setReadMessage(boolean readMessage);

}