/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LegalDraftDocument service. Represents a row in the &quot;ecoit_doc_LegalDraftDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ecoit.elegaldocument.model.impl.LegalDraftDocumentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ecoit.elegaldocument.model.impl.LegalDraftDocumentImpl</code>.
 * </p>
 *
 * @author Liverpool
 * @see LegalDraftDocument
 * @generated
 */
@ProviderType
public interface LegalDraftDocumentModel
	extends BaseModel<LegalDraftDocument>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal draft document model instance should use the {@link LegalDraftDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this legal draft document.
	 *
	 * @return the primary key of this legal draft document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legal draft document.
	 *
	 * @param primaryKey the primary key of this legal draft document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the draft ID of this legal draft document.
	 *
	 * @return the draft ID of this legal draft document
	 */
	public long getDraftId();

	/**
	 * Sets the draft ID of this legal draft document.
	 *
	 * @param draftId the draft ID of this legal draft document
	 */
	public void setDraftId(long draftId);

	/**
	 * Returns the group ID of this legal draft document.
	 *
	 * @return the group ID of this legal draft document
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this legal draft document.
	 *
	 * @param groupId the group ID of this legal draft document
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this legal draft document.
	 *
	 * @return the company ID of this legal draft document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this legal draft document.
	 *
	 * @param companyId the company ID of this legal draft document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this legal draft document.
	 *
	 * @return the user ID of this legal draft document
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this legal draft document.
	 *
	 * @param userId the user ID of this legal draft document
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this legal draft document.
	 *
	 * @return the user uuid of this legal draft document
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this legal draft document.
	 *
	 * @param userUuid the user uuid of this legal draft document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created by user of this legal draft document.
	 *
	 * @return the created by user of this legal draft document
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this legal draft document.
	 *
	 * @param createdByUser the created by user of this legal draft document
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Returns the created date of this legal draft document.
	 *
	 * @return the created date of this legal draft document
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this legal draft document.
	 *
	 * @param createdDate the created date of this legal draft document
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified by user of this legal draft document.
	 *
	 * @return the modified by user of this legal draft document
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this legal draft document.
	 *
	 * @param modifiedByUser the modified by user of this legal draft document
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Returns the modified date of this legal draft document.
	 *
	 * @return the modified date of this legal draft document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legal draft document.
	 *
	 * @param modifiedDate the modified date of this legal draft document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the approved by user of this legal draft document.
	 *
	 * @return the approved by user of this legal draft document
	 */
	public long getApprovedByUser();

	/**
	 * Sets the approved by user of this legal draft document.
	 *
	 * @param approvedByUser the approved by user of this legal draft document
	 */
	public void setApprovedByUser(long approvedByUser);

	/**
	 * Returns the approved date of this legal draft document.
	 *
	 * @return the approved date of this legal draft document
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this legal draft document.
	 *
	 * @param approvedDate the approved date of this legal draft document
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the published by user of this legal draft document.
	 *
	 * @return the published by user of this legal draft document
	 */
	public long getPublishedByUser();

	/**
	 * Sets the published by user of this legal draft document.
	 *
	 * @param publishedByUser the published by user of this legal draft document
	 */
	public void setPublishedByUser(long publishedByUser);

	/**
	 * Returns the published date of this legal draft document.
	 *
	 * @return the published date of this legal draft document
	 */
	public Date getPublishedDate();

	/**
	 * Sets the published date of this legal draft document.
	 *
	 * @param publishedDate the published date of this legal draft document
	 */
	public void setPublishedDate(Date publishedDate);

	/**
	 * Returns the title of this legal draft document.
	 *
	 * @return the title of this legal draft document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this legal draft document.
	 *
	 * @param title the title of this legal draft document
	 */
	public void setTitle(String title);

	/**
	 * Returns the expired date of this legal draft document.
	 *
	 * @return the expired date of this legal draft document
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this legal draft document.
	 *
	 * @param expiredDate the expired date of this legal draft document
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Returns the language of this legal draft document.
	 *
	 * @return the language of this legal draft document
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this legal draft document.
	 *
	 * @param language the language of this legal draft document
	 */
	public void setLanguage(String language);

	/**
	 * Returns the content of this legal draft document.
	 *
	 * @return the content of this legal draft document
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this legal draft document.
	 *
	 * @param content the content of this legal draft document
	 */
	public void setContent(String content);

	/**
	 * Returns the type ID of this legal draft document.
	 *
	 * @return the type ID of this legal draft document
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this legal draft document.
	 *
	 * @param typeId the type ID of this legal draft document
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the field ID of this legal draft document.
	 *
	 * @return the field ID of this legal draft document
	 */
	public long getFieldId();

	/**
	 * Sets the field ID of this legal draft document.
	 *
	 * @param fieldId the field ID of this legal draft document
	 */
	public void setFieldId(long fieldId);

	/**
	 * Returns the draft level of this legal draft document.
	 *
	 * @return the draft level of this legal draft document
	 */
	public int getDraftLevel();

	/**
	 * Sets the draft level of this legal draft document.
	 *
	 * @param draftLevel the draft level of this legal draft document
	 */
	public void setDraftLevel(int draftLevel);

	/**
	 * Returns the doc code of this legal draft document.
	 *
	 * @return the doc code of this legal draft document
	 */
	@AutoEscape
	public String getDocCode();

	/**
	 * Sets the doc code of this legal draft document.
	 *
	 * @param docCode the doc code of this legal draft document
	 */
	public void setDocCode(String docCode);

	/**
	 * Returns the status draft of this legal draft document.
	 *
	 * @return the status draft of this legal draft document
	 */
	public int getStatusDraft();

	/**
	 * Sets the status draft of this legal draft document.
	 *
	 * @param statusDraft the status draft of this legal draft document
	 */
	public void setStatusDraft(int statusDraft);

	/**
	 * Returns the email of this legal draft document.
	 *
	 * @return the email of this legal draft document
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this legal draft document.
	 *
	 * @param email the email of this legal draft document
	 */
	public void setEmail(String email);

	/**
	 * Returns the destination of this legal draft document.
	 *
	 * @return the destination of this legal draft document
	 */
	@AutoEscape
	public String getDestination();

	/**
	 * Sets the destination of this legal draft document.
	 *
	 * @param destination the destination of this legal draft document
	 */
	public void setDestination(String destination);

}