/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model;

import com.ecoit.elegaldocument.service.persistence.LegalTDRelPK;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LegalTDRel service. Represents a row in the &quot;ecoit_doc_LegalTDRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ecoit.elegaldocument.model.impl.LegalTDRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ecoit.elegaldocument.model.impl.LegalTDRelImpl</code>.
 * </p>
 *
 * @author Liverpool
 * @see LegalTDRel
 * @generated
 */
@ProviderType
public interface LegalTDRelModel extends BaseModel<LegalTDRel> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal td rel model instance should use the {@link LegalTDRel} interface instead.
	 */

	/**
	 * Returns the primary key of this legal td rel.
	 *
	 * @return the primary key of this legal td rel
	 */
	public LegalTDRelPK getPrimaryKey();

	/**
	 * Sets the primary key of this legal td rel.
	 *
	 * @param primaryKey the primary key of this legal td rel
	 */
	public void setPrimaryKey(LegalTDRelPK primaryKey);

	/**
	 * Returns the doc ID of this legal td rel.
	 *
	 * @return the doc ID of this legal td rel
	 */
	public long getDocId();

	/**
	 * Sets the doc ID of this legal td rel.
	 *
	 * @param docId the doc ID of this legal td rel
	 */
	public void setDocId(long docId);

	/**
	 * Returns the tag ID of this legal td rel.
	 *
	 * @return the tag ID of this legal td rel
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this legal td rel.
	 *
	 * @param tagId the tag ID of this legal td rel
	 */
	public void setTagId(long tagId);

}