/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package User.Rank.Poisition.Service.service.base;

import User.Rank.Poisition.Service.model.UserPoisition_Dang;
import User.Rank.Poisition.Service.service.UserPoisition_DangLocalService;
import User.Rank.Poisition.Service.service.persistence.UserChucDanhPersistence;
import User.Rank.Poisition.Service.service.persistence.UserPoisitionPersistence;
import User.Rank.Poisition.Service.service.persistence.UserPoisition_DangPersistence;
import User.Rank.Poisition.Service.service.persistence.UserRankPersistence;
import User.Rank.Poisition.Service.service.persistence.UserRankPositionPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.annotation.versioning.ProviderType;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the user poisition_ dang local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link User.Rank.Poisition.Service.service.impl.UserPoisition_DangLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see User.Rank.Poisition.Service.service.impl.UserPoisition_DangLocalServiceImpl
 * @generated
 */
@ProviderType
public abstract class UserPoisition_DangLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements UserPoisition_DangLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>UserPoisition_DangLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>User.Rank.Poisition.Service.service.UserPoisition_DangLocalServiceUtil</code>.
	 */

	/**
	 * Adds the user poisition_ dang to the database. Also notifies the appropriate model listeners.
	 *
	 * @param userPoisition_Dang the user poisition_ dang
	 * @return the user poisition_ dang that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UserPoisition_Dang addUserPoisition_Dang(
		UserPoisition_Dang userPoisition_Dang) {

		userPoisition_Dang.setNew(true);

		return userPoisition_DangPersistence.update(userPoisition_Dang);
	}

	/**
	 * Creates a new user poisition_ dang with the primary key. Does not add the user poisition_ dang to the database.
	 *
	 * @param userPoisitionDangId the primary key for the new user poisition_ dang
	 * @return the new user poisition_ dang
	 */
	@Override
	@Transactional(enabled = false)
	public UserPoisition_Dang createUserPoisition_Dang(
		long userPoisitionDangId) {

		return userPoisition_DangPersistence.create(userPoisitionDangId);
	}

	/**
	 * Deletes the user poisition_ dang with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param userPoisitionDangId the primary key of the user poisition_ dang
	 * @return the user poisition_ dang that was removed
	 * @throws PortalException if a user poisition_ dang with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UserPoisition_Dang deleteUserPoisition_Dang(long userPoisitionDangId)
		throws PortalException {

		return userPoisition_DangPersistence.remove(userPoisitionDangId);
	}

	/**
	 * Deletes the user poisition_ dang from the database. Also notifies the appropriate model listeners.
	 *
	 * @param userPoisition_Dang the user poisition_ dang
	 * @return the user poisition_ dang that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UserPoisition_Dang deleteUserPoisition_Dang(
		UserPoisition_Dang userPoisition_Dang) {

		return userPoisition_DangPersistence.remove(userPoisition_Dang);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			UserPoisition_Dang.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return userPoisition_DangPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>User.Rank.Poisition.Service.model.impl.UserPoisition_DangModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return userPoisition_DangPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>User.Rank.Poisition.Service.model.impl.UserPoisition_DangModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return userPoisition_DangPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return userPoisition_DangPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return userPoisition_DangPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public UserPoisition_Dang fetchUserPoisition_Dang(
		long userPoisitionDangId) {

		return userPoisition_DangPersistence.fetchByPrimaryKey(
			userPoisitionDangId);
	}

	/**
	 * Returns the user poisition_ dang matching the UUID and group.
	 *
	 * @param uuid the user poisition_ dang's UUID
	 * @param groupId the primary key of the group
	 * @return the matching user poisition_ dang, or <code>null</code> if a matching user poisition_ dang could not be found
	 */
	@Override
	public UserPoisition_Dang fetchUserPoisition_DangByUuidAndGroupId(
		String uuid, long groupId) {

		return userPoisition_DangPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the user poisition_ dang with the primary key.
	 *
	 * @param userPoisitionDangId the primary key of the user poisition_ dang
	 * @return the user poisition_ dang
	 * @throws PortalException if a user poisition_ dang with the primary key could not be found
	 */
	@Override
	public UserPoisition_Dang getUserPoisition_Dang(long userPoisitionDangId)
		throws PortalException {

		return userPoisition_DangPersistence.findByPrimaryKey(
			userPoisitionDangId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			userPoisition_DangLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UserPoisition_Dang.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("userPoisitionDangId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			userPoisition_DangLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(UserPoisition_Dang.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"userPoisitionDangId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			userPoisition_DangLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UserPoisition_Dang.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("userPoisitionDangId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<UserPoisition_Dang>() {

				@Override
				public void performAction(UserPoisition_Dang userPoisition_Dang)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, userPoisition_Dang);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(UserPoisition_Dang.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return userPoisition_DangLocalService.deleteUserPoisition_Dang(
			(UserPoisition_Dang)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return userPoisition_DangPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the user poisition_ dangs matching the UUID and company.
	 *
	 * @param uuid the UUID of the user poisition_ dangs
	 * @param companyId the primary key of the company
	 * @return the matching user poisition_ dangs, or an empty list if no matches were found
	 */
	@Override
	public List<UserPoisition_Dang> getUserPoisition_DangsByUuidAndCompanyId(
		String uuid, long companyId) {

		return userPoisition_DangPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of user poisition_ dangs matching the UUID and company.
	 *
	 * @param uuid the UUID of the user poisition_ dangs
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of user poisition_ dangs
	 * @param end the upper bound of the range of user poisition_ dangs (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching user poisition_ dangs, or an empty list if no matches were found
	 */
	@Override
	public List<UserPoisition_Dang> getUserPoisition_DangsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<UserPoisition_Dang> orderByComparator) {

		return userPoisition_DangPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the user poisition_ dang matching the UUID and group.
	 *
	 * @param uuid the user poisition_ dang's UUID
	 * @param groupId the primary key of the group
	 * @return the matching user poisition_ dang
	 * @throws PortalException if a matching user poisition_ dang could not be found
	 */
	@Override
	public UserPoisition_Dang getUserPoisition_DangByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return userPoisition_DangPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the user poisition_ dangs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>User.Rank.Poisition.Service.model.impl.UserPoisition_DangModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of user poisition_ dangs
	 * @param end the upper bound of the range of user poisition_ dangs (not inclusive)
	 * @return the range of user poisition_ dangs
	 */
	@Override
	public List<UserPoisition_Dang> getUserPoisition_Dangs(int start, int end) {
		return userPoisition_DangPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of user poisition_ dangs.
	 *
	 * @return the number of user poisition_ dangs
	 */
	@Override
	public int getUserPoisition_DangsCount() {
		return userPoisition_DangPersistence.countAll();
	}

	/**
	 * Updates the user poisition_ dang in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param userPoisition_Dang the user poisition_ dang
	 * @return the user poisition_ dang that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UserPoisition_Dang updateUserPoisition_Dang(
		UserPoisition_Dang userPoisition_Dang) {

		return userPoisition_DangPersistence.update(userPoisition_Dang);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			UserPoisition_DangLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		userPoisition_DangLocalService =
			(UserPoisition_DangLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UserPoisition_DangLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UserPoisition_Dang.class;
	}

	protected String getModelClassName() {
		return UserPoisition_Dang.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				userPoisition_DangPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@Reference
	protected UserChucDanhPersistence userChucDanhPersistence;

	@Reference
	protected UserPoisitionPersistence userPoisitionPersistence;

	protected UserPoisition_DangLocalService userPoisition_DangLocalService;

	@Reference
	protected UserPoisition_DangPersistence userPoisition_DangPersistence;

	@Reference
	protected UserRankPersistence userRankPersistence;

	@Reference
	protected UserRankPositionPersistence userRankPositionPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}