/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.qa.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Question service. Represents a row in the &quot;ecoit_qa_Question&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ecoit.qa.service.model.impl.QuestionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ecoit.qa.service.model.impl.QuestionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Question
 * @generated
 */
@ProviderType
public interface QuestionModel
	extends BaseModel<Question>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question model instance should use the {@link Question} interface instead.
	 */

	/**
	 * Returns the primary key of this question.
	 *
	 * @return the primary key of this question
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question.
	 *
	 * @param primaryKey the primary key of this question
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this question.
	 *
	 * @return the uuid of this question
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this question.
	 *
	 * @param uuid the uuid of this question
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the question ID of this question.
	 *
	 * @return the question ID of this question
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this question.
	 *
	 * @param questionId the question ID of this question
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the group ID of this question.
	 *
	 * @return the group ID of this question
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this question.
	 *
	 * @param groupId the group ID of this question
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this question.
	 *
	 * @return the company ID of this question
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this question.
	 *
	 * @param companyId the company ID of this question
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this question.
	 *
	 * @return the user ID of this question
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this question.
	 *
	 * @param userId the user ID of this question
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this question.
	 *
	 * @return the user uuid of this question
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this question.
	 *
	 * @param userUuid the user uuid of this question
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this question.
	 *
	 * @return the user name of this question
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this question.
	 *
	 * @param userName the user name of this question
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this question.
	 *
	 * @return the create date of this question
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this question.
	 *
	 * @param createDate the create date of this question
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this question.
	 *
	 * @return the modified date of this question
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this question.
	 *
	 * @param modifiedDate the modified date of this question
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by user of this question.
	 *
	 * @return the modified by user of this question
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this question.
	 *
	 * @param modifiedByUser the modified by user of this question
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Returns the language of this question.
	 *
	 * @return the language of this question
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this question.
	 *
	 * @param language the language of this question
	 */
	public void setLanguage(String language);

	/**
	 * Returns the title of this question.
	 *
	 * @return the title of this question
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this question.
	 *
	 * @param title the title of this question
	 */
	public void setTitle(String title);

	/**
	 * Returns the email of this question.
	 *
	 * @return the email of this question
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this question.
	 *
	 * @param email the email of this question
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone number of this question.
	 *
	 * @return the phone number of this question
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this question.
	 *
	 * @param phoneNumber the phone number of this question
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the address of this question.
	 *
	 * @return the address of this question
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this question.
	 *
	 * @param address the address of this question
	 */
	public void setAddress(String address);

	/**
	 * Returns the view of this question.
	 *
	 * @return the view of this question
	 */
	public long getView();

	/**
	 * Sets the view of this question.
	 *
	 * @param view the view of this question
	 */
	public void setView(long view);

	/**
	 * Returns the content of this question.
	 *
	 * @return the content of this question
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this question.
	 *
	 * @param content the content of this question
	 */
	public void setContent(String content);

	/**
	 * Returns the attachment ID of this question.
	 *
	 * @return the attachment ID of this question
	 */
	public long getAttachmentId();

	/**
	 * Sets the attachment ID of this question.
	 *
	 * @param attachmentId the attachment ID of this question
	 */
	public void setAttachmentId(long attachmentId);

	/**
	 * Returns the category ID of this question.
	 *
	 * @return the category ID of this question
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this question.
	 *
	 * @param categoryId the category ID of this question
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the status of this question.
	 *
	 * @return the status of this question
	 */
	public int getStatus();

	/**
	 * Sets the status of this question.
	 *
	 * @param status the status of this question
	 */
	public void setStatus(int status);

}