/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package organizationalStructure.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the members service. Represents a row in the &quot;portal_members&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>organizationalStructure.service.model.impl.membersModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>organizationalStructure.service.model.impl.membersImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see members
 * @generated
 */
@ProviderType
public interface membersModel extends BaseModel<members> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a members model instance should use the {@link members} interface instead.
	 */

	/**
	 * Returns the primary key of this members.
	 *
	 * @return the primary key of this members
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this members.
	 *
	 * @param primaryKey the primary key of this members
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this members.
	 *
	 * @return the uuid of this members
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this members.
	 *
	 * @param uuid the uuid of this members
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the member ID of this members.
	 *
	 * @return the member ID of this members
	 */
	public long getMemberId();

	/**
	 * Sets the member ID of this members.
	 *
	 * @param memberId the member ID of this members
	 */
	public void setMemberId(long memberId);

	/**
	 * Returns the group ID of this members.
	 *
	 * @return the group ID of this members
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this members.
	 *
	 * @param groupId the group ID of this members
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the organization ID of this members.
	 *
	 * @return the organization ID of this members
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this members.
	 *
	 * @param organizationId the organization ID of this members
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the full name of this members.
	 *
	 * @return the full name of this members
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this members.
	 *
	 * @param fullName the full name of this members
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the birthday of this members.
	 *
	 * @return the birthday of this members
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this members.
	 *
	 * @param birthday the birthday of this members
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the address of this members.
	 *
	 * @return the address of this members
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this members.
	 *
	 * @param address the address of this members
	 */
	public void setAddress(String address);

	/**
	 * Returns the sex of this members.
	 *
	 * @return the sex of this members
	 */
	public Boolean getSex();

	/**
	 * Sets the sex of this members.
	 *
	 * @param sex the sex of this members
	 */
	public void setSex(Boolean sex);

	/**
	 * Returns the position of this members.
	 *
	 * @return the position of this members
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this members.
	 *
	 * @param position the position of this members
	 */
	public void setPosition(String position);

	/**
	 * Returns the create date of this members.
	 *
	 * @return the create date of this members
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this members.
	 *
	 * @param createDate the create date of this members
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the create user of this members.
	 *
	 * @return the create user of this members
	 */
	public long getCreateUser();

	/**
	 * Sets the create user of this members.
	 *
	 * @param createUser the create user of this members
	 */
	public void setCreateUser(long createUser);

	/**
	 * Returns the modified user of this members.
	 *
	 * @return the modified user of this members
	 */
	public long getModifiedUser();

	/**
	 * Sets the modified user of this members.
	 *
	 * @param modifiedUser the modified user of this members
	 */
	public void setModifiedUser(long modifiedUser);

	/**
	 * Returns the modified date of this members.
	 *
	 * @return the modified date of this members
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this members.
	 *
	 * @param modifiedDate the modified date of this members
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the is leader of this members.
	 *
	 * @return the is leader of this members
	 */
	public Boolean getIsLeader();

	/**
	 * Sets the is leader of this members.
	 *
	 * @param isLeader the is leader of this members
	 */
	public void setIsLeader(Boolean isLeader);

	/**
	 * Returns the url image of this members.
	 *
	 * @return the url image of this members
	 */
	@AutoEscape
	public String getUrlImage();

	/**
	 * Sets the url image of this members.
	 *
	 * @param urlImage the url image of this members
	 */
	public void setUrlImage(String urlImage);

	/**
	 * Returns the folder ID of this members.
	 *
	 * @return the folder ID of this members
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this members.
	 *
	 * @param folderId the folder ID of this members
	 */
	public void setFolderId(long folderId);

	/**
	 * Returns the image file ID of this members.
	 *
	 * @return the image file ID of this members
	 */
	public long getImageFileId();

	/**
	 * Sets the image file ID of this members.
	 *
	 * @param imageFileId the image file ID of this members
	 */
	public void setImageFileId(long imageFileId);

}