/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package User.Rank.Poisition.Service.model.impl;

import User.Rank.Poisition.Service.model.UserChucDanh;
import User.Rank.Poisition.Service.model.UserChucDanhModel;
import User.Rank.Poisition.Service.model.UserChucDanhSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the UserChucDanh service. Represents a row in the &quot;portal_user_UserChucDanh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>UserChucDanhModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserChucDanhImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserChucDanhImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class UserChucDanhModelImpl
	extends BaseModelImpl<UserChucDanh> implements UserChucDanhModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user chuc danh model instance should use the <code>UserChucDanh</code> interface instead.
	 */
	public static final String TABLE_NAME = "portal_user_UserChucDanh";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"userChucDanhId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userChucDanhName", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"totalMember", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userChucDanhId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userChucDanhName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("totalMember", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table portal_user_UserChucDanh (uuid_ VARCHAR(75) null,userChucDanhId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userChucDanhName VARCHAR(75) null,description VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,totalMember LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table portal_user_UserChucDanh";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userChucDanh.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY portal_user_UserChucDanh.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UserChucDanh toModel(UserChucDanhSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UserChucDanh model = new UserChucDanhImpl();

		model.setUuid(soapModel.getUuid());
		model.setUserChucDanhId(soapModel.getUserChucDanhId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserChucDanhName(soapModel.getUserChucDanhName());
		model.setDescription(soapModel.getDescription());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTotalMember(soapModel.getTotalMember());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UserChucDanh> toModels(UserChucDanhSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UserChucDanh> models = new ArrayList<UserChucDanh>(
			soapModels.length);

		for (UserChucDanhSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public UserChucDanhModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userChucDanhId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserChucDanhId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userChucDanhId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserChucDanh.class;
	}

	@Override
	public String getModelClassName() {
		return UserChucDanh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserChucDanh, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserChucDanh, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserChucDanh, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserChucDanh)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserChucDanh, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserChucDanh, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserChucDanh)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserChucDanh, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserChucDanh, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, UserChucDanh>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			UserChucDanh.class.getClassLoader(), UserChucDanh.class,
			ModelWrapper.class);

		try {
			Constructor<UserChucDanh> constructor =
				(Constructor<UserChucDanh>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<UserChucDanh, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UserChucDanh, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UserChucDanh, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<UserChucDanh, Object>>();
		Map<String, BiConsumer<UserChucDanh, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<UserChucDanh, ?>>();

		attributeGetterFunctions.put("uuid", UserChucDanh::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<UserChucDanh, String>)UserChucDanh::setUuid);
		attributeGetterFunctions.put(
			"userChucDanhId", UserChucDanh::getUserChucDanhId);
		attributeSetterBiConsumers.put(
			"userChucDanhId",
			(BiConsumer<UserChucDanh, Long>)UserChucDanh::setUserChucDanhId);
		attributeGetterFunctions.put("groupId", UserChucDanh::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<UserChucDanh, Long>)UserChucDanh::setGroupId);
		attributeGetterFunctions.put("companyId", UserChucDanh::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<UserChucDanh, Long>)UserChucDanh::setCompanyId);
		attributeGetterFunctions.put("userId", UserChucDanh::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<UserChucDanh, Long>)UserChucDanh::setUserId);
		attributeGetterFunctions.put(
			"userChucDanhName", UserChucDanh::getUserChucDanhName);
		attributeSetterBiConsumers.put(
			"userChucDanhName",
			(BiConsumer<UserChucDanh, String>)
				UserChucDanh::setUserChucDanhName);
		attributeGetterFunctions.put(
			"description", UserChucDanh::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<UserChucDanh, String>)UserChucDanh::setDescription);
		attributeGetterFunctions.put("createDate", UserChucDanh::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<UserChucDanh, Date>)UserChucDanh::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", UserChucDanh::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<UserChucDanh, Date>)UserChucDanh::setModifiedDate);
		attributeGetterFunctions.put(
			"totalMember", UserChucDanh::getTotalMember);
		attributeSetterBiConsumers.put(
			"totalMember",
			(BiConsumer<UserChucDanh, Long>)UserChucDanh::setTotalMember);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getUserChucDanhId() {
		return _userChucDanhId;
	}

	@Override
	public void setUserChucDanhId(long userChucDanhId) {
		_userChucDanhId = userChucDanhId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserChucDanhName() {
		if (_userChucDanhName == null) {
			return "";
		}
		else {
			return _userChucDanhName;
		}
	}

	@Override
	public void setUserChucDanhName(String userChucDanhName) {
		_userChucDanhName = userChucDanhName;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getTotalMember() {
		return _totalMember;
	}

	@Override
	public void setTotalMember(long totalMember) {
		_totalMember = totalMember;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(UserChucDanh.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UserChucDanh.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserChucDanh toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserChucDanh>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserChucDanhImpl userChucDanhImpl = new UserChucDanhImpl();

		userChucDanhImpl.setUuid(getUuid());
		userChucDanhImpl.setUserChucDanhId(getUserChucDanhId());
		userChucDanhImpl.setGroupId(getGroupId());
		userChucDanhImpl.setCompanyId(getCompanyId());
		userChucDanhImpl.setUserId(getUserId());
		userChucDanhImpl.setUserChucDanhName(getUserChucDanhName());
		userChucDanhImpl.setDescription(getDescription());
		userChucDanhImpl.setCreateDate(getCreateDate());
		userChucDanhImpl.setModifiedDate(getModifiedDate());
		userChucDanhImpl.setTotalMember(getTotalMember());

		userChucDanhImpl.resetOriginalValues();

		return userChucDanhImpl;
	}

	@Override
	public int compareTo(UserChucDanh userChucDanh) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), userChucDanh.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UserChucDanh)) {
			return false;
		}

		UserChucDanh userChucDanh = (UserChucDanh)obj;

		long primaryKey = userChucDanh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		UserChucDanhModelImpl userChucDanhModelImpl = this;

		userChucDanhModelImpl._originalUuid = userChucDanhModelImpl._uuid;

		userChucDanhModelImpl._originalGroupId = userChucDanhModelImpl._groupId;

		userChucDanhModelImpl._setOriginalGroupId = false;

		userChucDanhModelImpl._originalCompanyId =
			userChucDanhModelImpl._companyId;

		userChucDanhModelImpl._setOriginalCompanyId = false;

		userChucDanhModelImpl._setModifiedDate = false;

		userChucDanhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UserChucDanh> toCacheModel() {
		UserChucDanhCacheModel userChucDanhCacheModel =
			new UserChucDanhCacheModel();

		userChucDanhCacheModel.uuid = getUuid();

		String uuid = userChucDanhCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			userChucDanhCacheModel.uuid = null;
		}

		userChucDanhCacheModel.userChucDanhId = getUserChucDanhId();

		userChucDanhCacheModel.groupId = getGroupId();

		userChucDanhCacheModel.companyId = getCompanyId();

		userChucDanhCacheModel.userId = getUserId();

		userChucDanhCacheModel.userChucDanhName = getUserChucDanhName();

		String userChucDanhName = userChucDanhCacheModel.userChucDanhName;

		if ((userChucDanhName != null) && (userChucDanhName.length() == 0)) {
			userChucDanhCacheModel.userChucDanhName = null;
		}

		userChucDanhCacheModel.description = getDescription();

		String description = userChucDanhCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			userChucDanhCacheModel.description = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			userChucDanhCacheModel.createDate = createDate.getTime();
		}
		else {
			userChucDanhCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userChucDanhCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			userChucDanhCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		userChucDanhCacheModel.totalMember = getTotalMember();

		return userChucDanhCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserChucDanh, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserChucDanh, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserChucDanh, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((UserChucDanh)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<UserChucDanh, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<UserChucDanh, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserChucDanh, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((UserChucDanh)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserChucDanh>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _userChucDanhId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userChucDanhName;
	private String _description;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _totalMember;
	private long _columnBitmask;
	private UserChucDanh _escapedModel;

}