/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model.impl;

import com.ecoit.elegaldocument.model.EcmsPGRelation;
import com.ecoit.elegaldocument.model.EcmsPGRelationModel;
import com.ecoit.elegaldocument.model.EcmsPGRelationSoap;
import com.ecoit.elegaldocument.service.persistence.EcmsPGRelationPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EcmsPGRelation service. Represents a row in the &quot;ecoit_doc_EcmsPGRelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EcmsPGRelationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EcmsPGRelationImpl}.
 * </p>
 *
 * @author Liverpool
 * @see EcmsPGRelationImpl
 * @generated
 */
@JSON(strict = true)
public class EcmsPGRelationModelImpl
	extends BaseModelImpl<EcmsPGRelation> implements EcmsPGRelationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ecms pg relation model instance should use the <code>EcmsPGRelation</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_doc_EcmsPGRelation";

	public static final Object[][] TABLE_COLUMNS = {
		{"groupUserId", Types.BIGINT}, {"permission", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("groupUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("permission", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_doc_EcmsPGRelation (groupUserId LONG not null,permission INTEGER not null,primary key (groupUserId, permission))";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_doc_EcmsPGRelation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ecmsPGRelation.id.groupUserId ASC, ecmsPGRelation.id.permission ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_doc_EcmsPGRelation.groupUserId ASC, ecoit_doc_EcmsPGRelation.permission ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GROUPUSERID_COLUMN_BITMASK = 1L;

	public static final long PERMISSION_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EcmsPGRelation toModel(EcmsPGRelationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EcmsPGRelation model = new EcmsPGRelationImpl();

		model.setGroupUserId(soapModel.getGroupUserId());
		model.setPermission(soapModel.getPermission());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EcmsPGRelation> toModels(
		EcmsPGRelationSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EcmsPGRelation> models = new ArrayList<EcmsPGRelation>(
			soapModels.length);

		for (EcmsPGRelationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EcmsPGRelationModelImpl() {
	}

	@Override
	public EcmsPGRelationPK getPrimaryKey() {
		return new EcmsPGRelationPK(_groupUserId, _permission);
	}

	@Override
	public void setPrimaryKey(EcmsPGRelationPK primaryKey) {
		setGroupUserId(primaryKey.groupUserId);
		setPermission(primaryKey.permission);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new EcmsPGRelationPK(_groupUserId, _permission);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((EcmsPGRelationPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return EcmsPGRelation.class;
	}

	@Override
	public String getModelClassName() {
		return EcmsPGRelation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EcmsPGRelation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EcmsPGRelation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EcmsPGRelation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EcmsPGRelation)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EcmsPGRelation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EcmsPGRelation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EcmsPGRelation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EcmsPGRelation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EcmsPGRelation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EcmsPGRelation>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EcmsPGRelation.class.getClassLoader(), EcmsPGRelation.class,
			ModelWrapper.class);

		try {
			Constructor<EcmsPGRelation> constructor =
				(Constructor<EcmsPGRelation>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EcmsPGRelation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EcmsPGRelation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EcmsPGRelation, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EcmsPGRelation, Object>>();
		Map<String, BiConsumer<EcmsPGRelation, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EcmsPGRelation, ?>>();

		attributeGetterFunctions.put(
			"groupUserId", EcmsPGRelation::getGroupUserId);
		attributeSetterBiConsumers.put(
			"groupUserId",
			(BiConsumer<EcmsPGRelation, Long>)EcmsPGRelation::setGroupUserId);
		attributeGetterFunctions.put(
			"permission", EcmsPGRelation::getPermission);
		attributeSetterBiConsumers.put(
			"permission",
			(BiConsumer<EcmsPGRelation, Integer>)EcmsPGRelation::setPermission);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getGroupUserId() {
		return _groupUserId;
	}

	@Override
	public void setGroupUserId(long groupUserId) {
		_columnBitmask |= GROUPUSERID_COLUMN_BITMASK;

		if (!_setOriginalGroupUserId) {
			_setOriginalGroupUserId = true;

			_originalGroupUserId = _groupUserId;
		}

		_groupUserId = groupUserId;
	}

	@Override
	public String getGroupUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getGroupUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setGroupUserUuid(String groupUserUuid) {
	}

	public long getOriginalGroupUserId() {
		return _originalGroupUserId;
	}

	@JSON
	@Override
	public int getPermission() {
		return _permission;
	}

	@Override
	public void setPermission(int permission) {
		_columnBitmask |= PERMISSION_COLUMN_BITMASK;

		if (!_setOriginalPermission) {
			_setOriginalPermission = true;

			_originalPermission = _permission;
		}

		_permission = permission;
	}

	public int getOriginalPermission() {
		return _originalPermission;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public EcmsPGRelation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EcmsPGRelation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EcmsPGRelationImpl ecmsPGRelationImpl = new EcmsPGRelationImpl();

		ecmsPGRelationImpl.setGroupUserId(getGroupUserId());
		ecmsPGRelationImpl.setPermission(getPermission());

		ecmsPGRelationImpl.resetOriginalValues();

		return ecmsPGRelationImpl;
	}

	@Override
	public int compareTo(EcmsPGRelation ecmsPGRelation) {
		EcmsPGRelationPK primaryKey = ecmsPGRelation.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EcmsPGRelation)) {
			return false;
		}

		EcmsPGRelation ecmsPGRelation = (EcmsPGRelation)obj;

		EcmsPGRelationPK primaryKey = ecmsPGRelation.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		EcmsPGRelationModelImpl ecmsPGRelationModelImpl = this;

		ecmsPGRelationModelImpl._originalGroupUserId =
			ecmsPGRelationModelImpl._groupUserId;

		ecmsPGRelationModelImpl._setOriginalGroupUserId = false;

		ecmsPGRelationModelImpl._originalPermission =
			ecmsPGRelationModelImpl._permission;

		ecmsPGRelationModelImpl._setOriginalPermission = false;

		ecmsPGRelationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EcmsPGRelation> toCacheModel() {
		EcmsPGRelationCacheModel ecmsPGRelationCacheModel =
			new EcmsPGRelationCacheModel();

		ecmsPGRelationCacheModel.ecmsPGRelationPK = getPrimaryKey();

		ecmsPGRelationCacheModel.groupUserId = getGroupUserId();

		ecmsPGRelationCacheModel.permission = getPermission();

		return ecmsPGRelationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EcmsPGRelation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EcmsPGRelation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EcmsPGRelation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EcmsPGRelation)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EcmsPGRelation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EcmsPGRelation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EcmsPGRelation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EcmsPGRelation)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EcmsPGRelation>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _groupUserId;
	private long _originalGroupUserId;
	private boolean _setOriginalGroupUserId;
	private int _permission;
	private int _originalPermission;
	private boolean _setOriginalPermission;
	private long _columnBitmask;
	private EcmsPGRelation _escapedModel;

}