/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model.impl;

import com.ecoit.elegaldocument.model.EcmsGroup;
import com.ecoit.elegaldocument.model.EcmsGroupModel;
import com.ecoit.elegaldocument.model.EcmsGroupSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EcmsGroup service. Represents a row in the &quot;ecoit_doc_EcmsGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EcmsGroupModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EcmsGroupImpl}.
 * </p>
 *
 * @author Liverpool
 * @see EcmsGroupImpl
 * @generated
 */
@JSON(strict = true)
public class EcmsGroupModelImpl
	extends BaseModelImpl<EcmsGroup> implements EcmsGroupModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ecms group model instance should use the <code>EcmsGroup</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_doc_EcmsGroup";

	public static final Object[][] TABLE_COLUMNS = {
		{"groupUserId", Types.BIGINT}, {"groupName", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"createdDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("groupUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_doc_EcmsGroup (groupUserId LONG not null primary key,groupName VARCHAR(250) null,description VARCHAR(550) null,groupId LONG,createdDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_doc_EcmsGroup";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ecmsGroup.groupUserId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_doc_EcmsGroup.groupUserId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GROUPUSERID_COLUMN_BITMASK = 1L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EcmsGroup toModel(EcmsGroupSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EcmsGroup model = new EcmsGroupImpl();

		model.setGroupUserId(soapModel.getGroupUserId());
		model.setGroupName(soapModel.getGroupName());
		model.setDescription(soapModel.getDescription());
		model.setGroupId(soapModel.getGroupId());
		model.setCreatedDate(soapModel.getCreatedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EcmsGroup> toModels(EcmsGroupSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EcmsGroup> models = new ArrayList<EcmsGroup>(soapModels.length);

		for (EcmsGroupSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EcmsGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _groupUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGroupUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _groupUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EcmsGroup.class;
	}

	@Override
	public String getModelClassName() {
		return EcmsGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EcmsGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EcmsGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EcmsGroup, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((EcmsGroup)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EcmsGroup, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EcmsGroup, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EcmsGroup)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EcmsGroup, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EcmsGroup, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EcmsGroup>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EcmsGroup.class.getClassLoader(), EcmsGroup.class,
			ModelWrapper.class);

		try {
			Constructor<EcmsGroup> constructor =
				(Constructor<EcmsGroup>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EcmsGroup, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EcmsGroup, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EcmsGroup, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EcmsGroup, Object>>();
		Map<String, BiConsumer<EcmsGroup, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EcmsGroup, ?>>();

		attributeGetterFunctions.put("groupUserId", EcmsGroup::getGroupUserId);
		attributeSetterBiConsumers.put(
			"groupUserId",
			(BiConsumer<EcmsGroup, Long>)EcmsGroup::setGroupUserId);
		attributeGetterFunctions.put("groupName", EcmsGroup::getGroupName);
		attributeSetterBiConsumers.put(
			"groupName",
			(BiConsumer<EcmsGroup, String>)EcmsGroup::setGroupName);
		attributeGetterFunctions.put("description", EcmsGroup::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<EcmsGroup, String>)EcmsGroup::setDescription);
		attributeGetterFunctions.put("groupId", EcmsGroup::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<EcmsGroup, Long>)EcmsGroup::setGroupId);
		attributeGetterFunctions.put("createdDate", EcmsGroup::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<EcmsGroup, Date>)EcmsGroup::setCreatedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getGroupUserId() {
		return _groupUserId;
	}

	@Override
	public void setGroupUserId(long groupUserId) {
		_columnBitmask |= GROUPUSERID_COLUMN_BITMASK;

		if (!_setOriginalGroupUserId) {
			_setOriginalGroupUserId = true;

			_originalGroupUserId = _groupUserId;
		}

		_groupUserId = groupUserId;
	}

	@Override
	public String getGroupUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getGroupUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setGroupUserUuid(String groupUserUuid) {
	}

	public long getOriginalGroupUserId() {
		return _originalGroupUserId;
	}

	@JSON
	@Override
	public String getGroupName() {
		if (_groupName == null) {
			return "";
		}
		else {
			return _groupName;
		}
	}

	@Override
	public void setGroupName(String groupName) {
		_groupName = groupName;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, EcmsGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EcmsGroup toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EcmsGroup>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EcmsGroupImpl ecmsGroupImpl = new EcmsGroupImpl();

		ecmsGroupImpl.setGroupUserId(getGroupUserId());
		ecmsGroupImpl.setGroupName(getGroupName());
		ecmsGroupImpl.setDescription(getDescription());
		ecmsGroupImpl.setGroupId(getGroupId());
		ecmsGroupImpl.setCreatedDate(getCreatedDate());

		ecmsGroupImpl.resetOriginalValues();

		return ecmsGroupImpl;
	}

	@Override
	public int compareTo(EcmsGroup ecmsGroup) {
		long primaryKey = ecmsGroup.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EcmsGroup)) {
			return false;
		}

		EcmsGroup ecmsGroup = (EcmsGroup)obj;

		long primaryKey = ecmsGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		EcmsGroupModelImpl ecmsGroupModelImpl = this;

		ecmsGroupModelImpl._originalGroupUserId =
			ecmsGroupModelImpl._groupUserId;

		ecmsGroupModelImpl._setOriginalGroupUserId = false;

		ecmsGroupModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EcmsGroup> toCacheModel() {
		EcmsGroupCacheModel ecmsGroupCacheModel = new EcmsGroupCacheModel();

		ecmsGroupCacheModel.groupUserId = getGroupUserId();

		ecmsGroupCacheModel.groupName = getGroupName();

		String groupName = ecmsGroupCacheModel.groupName;

		if ((groupName != null) && (groupName.length() == 0)) {
			ecmsGroupCacheModel.groupName = null;
		}

		ecmsGroupCacheModel.description = getDescription();

		String description = ecmsGroupCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			ecmsGroupCacheModel.description = null;
		}

		ecmsGroupCacheModel.groupId = getGroupId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			ecmsGroupCacheModel.createdDate = createdDate.getTime();
		}
		else {
			ecmsGroupCacheModel.createdDate = Long.MIN_VALUE;
		}

		return ecmsGroupCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EcmsGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EcmsGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EcmsGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EcmsGroup)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EcmsGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EcmsGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EcmsGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EcmsGroup)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EcmsGroup>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _groupUserId;
	private long _originalGroupUserId;
	private boolean _setOriginalGroupUserId;
	private String _groupName;
	private String _description;
	private long _groupId;
	private Date _createdDate;
	private long _columnBitmask;
	private EcmsGroup _escapedModel;

}