/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model.impl;

import com.ecoit.elegaldocument.model.GroupCategory;
import com.ecoit.elegaldocument.model.GroupCategoryModel;
import com.ecoit.elegaldocument.model.GroupCategorySoap;
import com.ecoit.elegaldocument.service.persistence.GroupCategoryPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GroupCategory service. Represents a row in the &quot;ecoit_doc_GroupCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GroupCategoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GroupCategoryImpl}.
 * </p>
 *
 * @author Liverpool
 * @see GroupCategoryImpl
 * @generated
 */
@JSON(strict = true)
public class GroupCategoryModelImpl
	extends BaseModelImpl<GroupCategory> implements GroupCategoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a group category model instance should use the <code>GroupCategory</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_doc_GroupCategory";

	public static final Object[][] TABLE_COLUMNS = {
		{"groupUserId", Types.BIGINT}, {"typeid", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("groupUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeid", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_doc_GroupCategory (groupUserId LONG not null,typeid LONG not null,primary key (groupUserId, typeid))";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_doc_GroupCategory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY groupCategory.id.groupUserId ASC, groupCategory.id.typeid ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_doc_GroupCategory.groupUserId ASC, ecoit_doc_GroupCategory.typeid ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GROUPUSERID_COLUMN_BITMASK = 1L;

	public static final long TYPEID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GroupCategory toModel(GroupCategorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GroupCategory model = new GroupCategoryImpl();

		model.setGroupUserId(soapModel.getGroupUserId());
		model.setTypeid(soapModel.getTypeid());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GroupCategory> toModels(GroupCategorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<GroupCategory> models = new ArrayList<GroupCategory>(
			soapModels.length);

		for (GroupCategorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GroupCategoryModelImpl() {
	}

	@Override
	public GroupCategoryPK getPrimaryKey() {
		return new GroupCategoryPK(_groupUserId, _typeid);
	}

	@Override
	public void setPrimaryKey(GroupCategoryPK primaryKey) {
		setGroupUserId(primaryKey.groupUserId);
		setTypeid(primaryKey.typeid);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new GroupCategoryPK(_groupUserId, _typeid);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((GroupCategoryPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return GroupCategory.class;
	}

	@Override
	public String getModelClassName() {
		return GroupCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GroupCategory, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GroupCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupCategory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GroupCategory)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GroupCategory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GroupCategory, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GroupCategory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GroupCategory, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GroupCategory, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GroupCategory>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GroupCategory.class.getClassLoader(), GroupCategory.class,
			ModelWrapper.class);

		try {
			Constructor<GroupCategory> constructor =
				(Constructor<GroupCategory>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GroupCategory, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GroupCategory, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GroupCategory, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GroupCategory, Object>>();
		Map<String, BiConsumer<GroupCategory, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GroupCategory, ?>>();

		attributeGetterFunctions.put(
			"groupUserId", GroupCategory::getGroupUserId);
		attributeSetterBiConsumers.put(
			"groupUserId",
			(BiConsumer<GroupCategory, Long>)GroupCategory::setGroupUserId);
		attributeGetterFunctions.put("typeid", GroupCategory::getTypeid);
		attributeSetterBiConsumers.put(
			"typeid",
			(BiConsumer<GroupCategory, Long>)GroupCategory::setTypeid);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getGroupUserId() {
		return _groupUserId;
	}

	@Override
	public void setGroupUserId(long groupUserId) {
		_columnBitmask |= GROUPUSERID_COLUMN_BITMASK;

		if (!_setOriginalGroupUserId) {
			_setOriginalGroupUserId = true;

			_originalGroupUserId = _groupUserId;
		}

		_groupUserId = groupUserId;
	}

	@Override
	public String getGroupUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getGroupUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setGroupUserUuid(String groupUserUuid) {
	}

	public long getOriginalGroupUserId() {
		return _originalGroupUserId;
	}

	@JSON
	@Override
	public long getTypeid() {
		return _typeid;
	}

	@Override
	public void setTypeid(long typeid) {
		_columnBitmask |= TYPEID_COLUMN_BITMASK;

		if (!_setOriginalTypeid) {
			_setOriginalTypeid = true;

			_originalTypeid = _typeid;
		}

		_typeid = typeid;
	}

	public long getOriginalTypeid() {
		return _originalTypeid;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public GroupCategory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GroupCategory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GroupCategoryImpl groupCategoryImpl = new GroupCategoryImpl();

		groupCategoryImpl.setGroupUserId(getGroupUserId());
		groupCategoryImpl.setTypeid(getTypeid());

		groupCategoryImpl.resetOriginalValues();

		return groupCategoryImpl;
	}

	@Override
	public int compareTo(GroupCategory groupCategory) {
		GroupCategoryPK primaryKey = groupCategory.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GroupCategory)) {
			return false;
		}

		GroupCategory groupCategory = (GroupCategory)obj;

		GroupCategoryPK primaryKey = groupCategory.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GroupCategoryModelImpl groupCategoryModelImpl = this;

		groupCategoryModelImpl._originalGroupUserId =
			groupCategoryModelImpl._groupUserId;

		groupCategoryModelImpl._setOriginalGroupUserId = false;

		groupCategoryModelImpl._originalTypeid = groupCategoryModelImpl._typeid;

		groupCategoryModelImpl._setOriginalTypeid = false;

		groupCategoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GroupCategory> toCacheModel() {
		GroupCategoryCacheModel groupCategoryCacheModel =
			new GroupCategoryCacheModel();

		groupCategoryCacheModel.groupCategoryPK = getPrimaryKey();

		groupCategoryCacheModel.groupUserId = getGroupUserId();

		groupCategoryCacheModel.typeid = getTypeid();

		return groupCategoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GroupCategory, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GroupCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GroupCategory)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GroupCategory, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GroupCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GroupCategory)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GroupCategory>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _groupUserId;
	private long _originalGroupUserId;
	private boolean _setOriginalGroupUserId;
	private long _typeid;
	private long _originalTypeid;
	private boolean _setOriginalTypeid;
	private long _columnBitmask;
	private GroupCategory _escapedModel;

}