/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model.impl;

import com.ecoit.elegaldocument.model.GroupOrganization;
import com.ecoit.elegaldocument.model.GroupOrganizationModel;
import com.ecoit.elegaldocument.model.GroupOrganizationSoap;
import com.ecoit.elegaldocument.service.persistence.GroupOrganizationPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GroupOrganization service. Represents a row in the &quot;ecoit_doc_GroupOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GroupOrganizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GroupOrganizationImpl}.
 * </p>
 *
 * @author Liverpool
 * @see GroupOrganizationImpl
 * @generated
 */
@JSON(strict = true)
public class GroupOrganizationModelImpl
	extends BaseModelImpl<GroupOrganization> implements GroupOrganizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a group organization model instance should use the <code>GroupOrganization</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_doc_GroupOrganization";

	public static final Object[][] TABLE_COLUMNS = {
		{"groupUserId", Types.BIGINT}, {"organizationid", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("groupUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationid", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_doc_GroupOrganization (groupUserId LONG not null,organizationid LONG not null,primary key (groupUserId, organizationid))";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_doc_GroupOrganization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY groupOrganization.id.groupUserId ASC, groupOrganization.id.organizationid ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_doc_GroupOrganization.groupUserId ASC, ecoit_doc_GroupOrganization.organizationid ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GROUPUSERID_COLUMN_BITMASK = 1L;

	public static final long ORGANIZATIONID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GroupOrganization toModel(GroupOrganizationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GroupOrganization model = new GroupOrganizationImpl();

		model.setGroupUserId(soapModel.getGroupUserId());
		model.setOrganizationid(soapModel.getOrganizationid());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GroupOrganization> toModels(
		GroupOrganizationSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<GroupOrganization> models = new ArrayList<GroupOrganization>(
			soapModels.length);

		for (GroupOrganizationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GroupOrganizationModelImpl() {
	}

	@Override
	public GroupOrganizationPK getPrimaryKey() {
		return new GroupOrganizationPK(_groupUserId, _organizationid);
	}

	@Override
	public void setPrimaryKey(GroupOrganizationPK primaryKey) {
		setGroupUserId(primaryKey.groupUserId);
		setOrganizationid(primaryKey.organizationid);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new GroupOrganizationPK(_groupUserId, _organizationid);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((GroupOrganizationPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return GroupOrganization.class;
	}

	@Override
	public String getModelClassName() {
		return GroupOrganization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GroupOrganization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GroupOrganization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupOrganization, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GroupOrganization)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GroupOrganization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GroupOrganization, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GroupOrganization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GroupOrganization, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GroupOrganization, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GroupOrganization>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GroupOrganization.class.getClassLoader(), GroupOrganization.class,
			ModelWrapper.class);

		try {
			Constructor<GroupOrganization> constructor =
				(Constructor<GroupOrganization>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GroupOrganization, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GroupOrganization, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GroupOrganization, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<GroupOrganization, Object>>();
		Map<String, BiConsumer<GroupOrganization, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<GroupOrganization, ?>>();

		attributeGetterFunctions.put(
			"groupUserId", GroupOrganization::getGroupUserId);
		attributeSetterBiConsumers.put(
			"groupUserId",
			(BiConsumer<GroupOrganization, Long>)
				GroupOrganization::setGroupUserId);
		attributeGetterFunctions.put(
			"organizationid", GroupOrganization::getOrganizationid);
		attributeSetterBiConsumers.put(
			"organizationid",
			(BiConsumer<GroupOrganization, Long>)
				GroupOrganization::setOrganizationid);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getGroupUserId() {
		return _groupUserId;
	}

	@Override
	public void setGroupUserId(long groupUserId) {
		_columnBitmask |= GROUPUSERID_COLUMN_BITMASK;

		if (!_setOriginalGroupUserId) {
			_setOriginalGroupUserId = true;

			_originalGroupUserId = _groupUserId;
		}

		_groupUserId = groupUserId;
	}

	@Override
	public String getGroupUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getGroupUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setGroupUserUuid(String groupUserUuid) {
	}

	public long getOriginalGroupUserId() {
		return _originalGroupUserId;
	}

	@JSON
	@Override
	public long getOrganizationid() {
		return _organizationid;
	}

	@Override
	public void setOrganizationid(long organizationid) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalOrganizationid) {
			_setOriginalOrganizationid = true;

			_originalOrganizationid = _organizationid;
		}

		_organizationid = organizationid;
	}

	public long getOriginalOrganizationid() {
		return _originalOrganizationid;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public GroupOrganization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GroupOrganization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GroupOrganizationImpl groupOrganizationImpl =
			new GroupOrganizationImpl();

		groupOrganizationImpl.setGroupUserId(getGroupUserId());
		groupOrganizationImpl.setOrganizationid(getOrganizationid());

		groupOrganizationImpl.resetOriginalValues();

		return groupOrganizationImpl;
	}

	@Override
	public int compareTo(GroupOrganization groupOrganization) {
		GroupOrganizationPK primaryKey = groupOrganization.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GroupOrganization)) {
			return false;
		}

		GroupOrganization groupOrganization = (GroupOrganization)obj;

		GroupOrganizationPK primaryKey = groupOrganization.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GroupOrganizationModelImpl groupOrganizationModelImpl = this;

		groupOrganizationModelImpl._originalGroupUserId =
			groupOrganizationModelImpl._groupUserId;

		groupOrganizationModelImpl._setOriginalGroupUserId = false;

		groupOrganizationModelImpl._originalOrganizationid =
			groupOrganizationModelImpl._organizationid;

		groupOrganizationModelImpl._setOriginalOrganizationid = false;

		groupOrganizationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GroupOrganization> toCacheModel() {
		GroupOrganizationCacheModel groupOrganizationCacheModel =
			new GroupOrganizationCacheModel();

		groupOrganizationCacheModel.groupOrganizationPK = getPrimaryKey();

		groupOrganizationCacheModel.groupUserId = getGroupUserId();

		groupOrganizationCacheModel.organizationid = getOrganizationid();

		return groupOrganizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GroupOrganization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GroupOrganization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupOrganization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GroupOrganization)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GroupOrganization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GroupOrganization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GroupOrganization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GroupOrganization)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GroupOrganization>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _groupUserId;
	private long _originalGroupUserId;
	private boolean _setOriginalGroupUserId;
	private long _organizationid;
	private long _originalOrganizationid;
	private boolean _setOriginalOrganizationid;
	private long _columnBitmask;
	private GroupOrganization _escapedModel;

}