/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model.impl;

import com.ecoit.elegaldocument.model.LegalDTypeRel;
import com.ecoit.elegaldocument.model.LegalDTypeRelModel;
import com.ecoit.elegaldocument.model.LegalDTypeRelSoap;
import com.ecoit.elegaldocument.service.persistence.LegalDTypeRelPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LegalDTypeRel service. Represents a row in the &quot;ecoit_doc_LegalDTypeRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LegalDTypeRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LegalDTypeRelImpl}.
 * </p>
 *
 * @author Liverpool
 * @see LegalDTypeRelImpl
 * @generated
 */
@JSON(strict = true)
public class LegalDTypeRelModelImpl
	extends BaseModelImpl<LegalDTypeRel> implements LegalDTypeRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a legal d type rel model instance should use the <code>LegalDTypeRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_doc_LegalDTypeRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"docId", Types.BIGINT}, {"typeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("docId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_doc_LegalDTypeRel (docId LONG not null,typeId LONG not null,primary key (docId, typeId))";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_doc_LegalDTypeRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY legalDTypeRel.id.docId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_doc_LegalDTypeRel.docId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DOCID_COLUMN_BITMASK = 1L;

	public static final long TYPEID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LegalDTypeRel toModel(LegalDTypeRelSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LegalDTypeRel model = new LegalDTypeRelImpl();

		model.setDocId(soapModel.getDocId());
		model.setTypeId(soapModel.getTypeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LegalDTypeRel> toModels(LegalDTypeRelSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LegalDTypeRel> models = new ArrayList<LegalDTypeRel>(
			soapModels.length);

		for (LegalDTypeRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LegalDTypeRelModelImpl() {
	}

	@Override
	public LegalDTypeRelPK getPrimaryKey() {
		return new LegalDTypeRelPK(_docId, _typeId);
	}

	@Override
	public void setPrimaryKey(LegalDTypeRelPK primaryKey) {
		setDocId(primaryKey.docId);
		setTypeId(primaryKey.typeId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new LegalDTypeRelPK(_docId, _typeId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((LegalDTypeRelPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return LegalDTypeRel.class;
	}

	@Override
	public String getModelClassName() {
		return LegalDTypeRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LegalDTypeRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LegalDTypeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDTypeRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LegalDTypeRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LegalDTypeRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LegalDTypeRel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LegalDTypeRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LegalDTypeRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LegalDTypeRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LegalDTypeRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LegalDTypeRel.class.getClassLoader(), LegalDTypeRel.class,
			ModelWrapper.class);

		try {
			Constructor<LegalDTypeRel> constructor =
				(Constructor<LegalDTypeRel>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LegalDTypeRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LegalDTypeRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LegalDTypeRel, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LegalDTypeRel, Object>>();
		Map<String, BiConsumer<LegalDTypeRel, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LegalDTypeRel, ?>>();

		attributeGetterFunctions.put("docId", LegalDTypeRel::getDocId);
		attributeSetterBiConsumers.put(
			"docId", (BiConsumer<LegalDTypeRel, Long>)LegalDTypeRel::setDocId);
		attributeGetterFunctions.put("typeId", LegalDTypeRel::getTypeId);
		attributeSetterBiConsumers.put(
			"typeId",
			(BiConsumer<LegalDTypeRel, Long>)LegalDTypeRel::setTypeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getDocId() {
		return _docId;
	}

	@Override
	public void setDocId(long docId) {
		_columnBitmask = -1L;

		if (!_setOriginalDocId) {
			_setOriginalDocId = true;

			_originalDocId = _docId;
		}

		_docId = docId;
	}

	public long getOriginalDocId() {
		return _originalDocId;
	}

	@JSON
	@Override
	public long getTypeId() {
		return _typeId;
	}

	@Override
	public void setTypeId(long typeId) {
		_columnBitmask |= TYPEID_COLUMN_BITMASK;

		if (!_setOriginalTypeId) {
			_setOriginalTypeId = true;

			_originalTypeId = _typeId;
		}

		_typeId = typeId;
	}

	public long getOriginalTypeId() {
		return _originalTypeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public LegalDTypeRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LegalDTypeRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LegalDTypeRelImpl legalDTypeRelImpl = new LegalDTypeRelImpl();

		legalDTypeRelImpl.setDocId(getDocId());
		legalDTypeRelImpl.setTypeId(getTypeId());

		legalDTypeRelImpl.resetOriginalValues();

		return legalDTypeRelImpl;
	}

	@Override
	public int compareTo(LegalDTypeRel legalDTypeRel) {
		int value = 0;

		if (getDocId() < legalDTypeRel.getDocId()) {
			value = -1;
		}
		else if (getDocId() > legalDTypeRel.getDocId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LegalDTypeRel)) {
			return false;
		}

		LegalDTypeRel legalDTypeRel = (LegalDTypeRel)obj;

		LegalDTypeRelPK primaryKey = legalDTypeRel.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		LegalDTypeRelModelImpl legalDTypeRelModelImpl = this;

		legalDTypeRelModelImpl._originalDocId = legalDTypeRelModelImpl._docId;

		legalDTypeRelModelImpl._setOriginalDocId = false;

		legalDTypeRelModelImpl._originalTypeId = legalDTypeRelModelImpl._typeId;

		legalDTypeRelModelImpl._setOriginalTypeId = false;

		legalDTypeRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LegalDTypeRel> toCacheModel() {
		LegalDTypeRelCacheModel legalDTypeRelCacheModel =
			new LegalDTypeRelCacheModel();

		legalDTypeRelCacheModel.legalDTypeRelPK = getPrimaryKey();

		legalDTypeRelCacheModel.docId = getDocId();

		legalDTypeRelCacheModel.typeId = getTypeId();

		return legalDTypeRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LegalDTypeRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LegalDTypeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDTypeRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LegalDTypeRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LegalDTypeRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LegalDTypeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDTypeRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LegalDTypeRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LegalDTypeRel>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _docId;
	private long _originalDocId;
	private boolean _setOriginalDocId;
	private long _typeId;
	private long _originalTypeId;
	private boolean _setOriginalTypeId;
	private long _columnBitmask;
	private LegalDTypeRel _escapedModel;

}