/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model.impl;

import com.ecoit.elegaldocument.model.LegalDSRel;
import com.ecoit.elegaldocument.model.LegalDSRelModel;
import com.ecoit.elegaldocument.model.LegalDSRelSoap;
import com.ecoit.elegaldocument.service.persistence.LegalDSRelPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LegalDSRel service. Represents a row in the &quot;ecoit_doc_LegalDSRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LegalDSRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LegalDSRelImpl}.
 * </p>
 *
 * @author Liverpool
 * @see LegalDSRelImpl
 * @generated
 */
@JSON(strict = true)
public class LegalDSRelModelImpl
	extends BaseModelImpl<LegalDSRel> implements LegalDSRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a legal ds rel model instance should use the <code>LegalDSRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_doc_LegalDSRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"docId", Types.BIGINT}, {"sigId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("docId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sigId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_doc_LegalDSRel (docId LONG not null,sigId LONG not null,primary key (docId, sigId))";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_doc_LegalDSRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY legalDSRel.id.docId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_doc_LegalDSRel.docId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DOCID_COLUMN_BITMASK = 1L;

	public static final long SIGID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LegalDSRel toModel(LegalDSRelSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LegalDSRel model = new LegalDSRelImpl();

		model.setDocId(soapModel.getDocId());
		model.setSigId(soapModel.getSigId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LegalDSRel> toModels(LegalDSRelSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LegalDSRel> models = new ArrayList<LegalDSRel>(soapModels.length);

		for (LegalDSRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LegalDSRelModelImpl() {
	}

	@Override
	public LegalDSRelPK getPrimaryKey() {
		return new LegalDSRelPK(_docId, _sigId);
	}

	@Override
	public void setPrimaryKey(LegalDSRelPK primaryKey) {
		setDocId(primaryKey.docId);
		setSigId(primaryKey.sigId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new LegalDSRelPK(_docId, _sigId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((LegalDSRelPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return LegalDSRel.class;
	}

	@Override
	public String getModelClassName() {
		return LegalDSRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LegalDSRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LegalDSRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDSRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LegalDSRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LegalDSRel, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LegalDSRel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LegalDSRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LegalDSRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LegalDSRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LegalDSRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LegalDSRel.class.getClassLoader(), LegalDSRel.class,
			ModelWrapper.class);

		try {
			Constructor<LegalDSRel> constructor =
				(Constructor<LegalDSRel>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LegalDSRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LegalDSRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LegalDSRel, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LegalDSRel, Object>>();
		Map<String, BiConsumer<LegalDSRel, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LegalDSRel, ?>>();

		attributeGetterFunctions.put("docId", LegalDSRel::getDocId);
		attributeSetterBiConsumers.put(
			"docId", (BiConsumer<LegalDSRel, Long>)LegalDSRel::setDocId);
		attributeGetterFunctions.put("sigId", LegalDSRel::getSigId);
		attributeSetterBiConsumers.put(
			"sigId", (BiConsumer<LegalDSRel, Long>)LegalDSRel::setSigId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getDocId() {
		return _docId;
	}

	@Override
	public void setDocId(long docId) {
		_columnBitmask = -1L;

		if (!_setOriginalDocId) {
			_setOriginalDocId = true;

			_originalDocId = _docId;
		}

		_docId = docId;
	}

	public long getOriginalDocId() {
		return _originalDocId;
	}

	@JSON
	@Override
	public long getSigId() {
		return _sigId;
	}

	@Override
	public void setSigId(long sigId) {
		_columnBitmask |= SIGID_COLUMN_BITMASK;

		if (!_setOriginalSigId) {
			_setOriginalSigId = true;

			_originalSigId = _sigId;
		}

		_sigId = sigId;
	}

	public long getOriginalSigId() {
		return _originalSigId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public LegalDSRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LegalDSRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LegalDSRelImpl legalDSRelImpl = new LegalDSRelImpl();

		legalDSRelImpl.setDocId(getDocId());
		legalDSRelImpl.setSigId(getSigId());

		legalDSRelImpl.resetOriginalValues();

		return legalDSRelImpl;
	}

	@Override
	public int compareTo(LegalDSRel legalDSRel) {
		int value = 0;

		if (getDocId() < legalDSRel.getDocId()) {
			value = -1;
		}
		else if (getDocId() > legalDSRel.getDocId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LegalDSRel)) {
			return false;
		}

		LegalDSRel legalDSRel = (LegalDSRel)obj;

		LegalDSRelPK primaryKey = legalDSRel.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		LegalDSRelModelImpl legalDSRelModelImpl = this;

		legalDSRelModelImpl._originalDocId = legalDSRelModelImpl._docId;

		legalDSRelModelImpl._setOriginalDocId = false;

		legalDSRelModelImpl._originalSigId = legalDSRelModelImpl._sigId;

		legalDSRelModelImpl._setOriginalSigId = false;

		legalDSRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LegalDSRel> toCacheModel() {
		LegalDSRelCacheModel legalDSRelCacheModel = new LegalDSRelCacheModel();

		legalDSRelCacheModel.legalDSRelPK = getPrimaryKey();

		legalDSRelCacheModel.docId = getDocId();

		legalDSRelCacheModel.sigId = getSigId();

		return legalDSRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LegalDSRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LegalDSRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDSRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LegalDSRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LegalDSRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LegalDSRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDSRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LegalDSRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LegalDSRel>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _docId;
	private long _originalDocId;
	private boolean _setOriginalDocId;
	private long _sigId;
	private long _originalSigId;
	private boolean _setOriginalSigId;
	private long _columnBitmask;
	private LegalDSRel _escapedModel;

}