/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model.impl;

import com.ecoit.elegaldocument.model.LegalDFRel;
import com.ecoit.elegaldocument.model.LegalDFRelModel;
import com.ecoit.elegaldocument.model.LegalDFRelSoap;
import com.ecoit.elegaldocument.service.persistence.LegalDFRelPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LegalDFRel service. Represents a row in the &quot;ecoit_doc_LegalDFRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LegalDFRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LegalDFRelImpl}.
 * </p>
 *
 * @author Liverpool
 * @see LegalDFRelImpl
 * @generated
 */
@JSON(strict = true)
public class LegalDFRelModelImpl
	extends BaseModelImpl<LegalDFRel> implements LegalDFRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a legal df rel model instance should use the <code>LegalDFRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_doc_LegalDFRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"docId", Types.BIGINT}, {"fieldId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("docId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fieldId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_doc_LegalDFRel (docId LONG not null,fieldId LONG not null,primary key (docId, fieldId))";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_doc_LegalDFRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY legalDFRel.id.docId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_doc_LegalDFRel.docId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DOCID_COLUMN_BITMASK = 1L;

	public static final long FIELDID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LegalDFRel toModel(LegalDFRelSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LegalDFRel model = new LegalDFRelImpl();

		model.setDocId(soapModel.getDocId());
		model.setFieldId(soapModel.getFieldId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LegalDFRel> toModels(LegalDFRelSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LegalDFRel> models = new ArrayList<LegalDFRel>(soapModels.length);

		for (LegalDFRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LegalDFRelModelImpl() {
	}

	@Override
	public LegalDFRelPK getPrimaryKey() {
		return new LegalDFRelPK(_docId, _fieldId);
	}

	@Override
	public void setPrimaryKey(LegalDFRelPK primaryKey) {
		setDocId(primaryKey.docId);
		setFieldId(primaryKey.fieldId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new LegalDFRelPK(_docId, _fieldId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((LegalDFRelPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return LegalDFRel.class;
	}

	@Override
	public String getModelClassName() {
		return LegalDFRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LegalDFRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LegalDFRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDFRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LegalDFRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LegalDFRel, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LegalDFRel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LegalDFRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LegalDFRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LegalDFRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LegalDFRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LegalDFRel.class.getClassLoader(), LegalDFRel.class,
			ModelWrapper.class);

		try {
			Constructor<LegalDFRel> constructor =
				(Constructor<LegalDFRel>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LegalDFRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LegalDFRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LegalDFRel, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LegalDFRel, Object>>();
		Map<String, BiConsumer<LegalDFRel, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LegalDFRel, ?>>();

		attributeGetterFunctions.put("docId", LegalDFRel::getDocId);
		attributeSetterBiConsumers.put(
			"docId", (BiConsumer<LegalDFRel, Long>)LegalDFRel::setDocId);
		attributeGetterFunctions.put("fieldId", LegalDFRel::getFieldId);
		attributeSetterBiConsumers.put(
			"fieldId", (BiConsumer<LegalDFRel, Long>)LegalDFRel::setFieldId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getDocId() {
		return _docId;
	}

	@Override
	public void setDocId(long docId) {
		_columnBitmask = -1L;

		if (!_setOriginalDocId) {
			_setOriginalDocId = true;

			_originalDocId = _docId;
		}

		_docId = docId;
	}

	public long getOriginalDocId() {
		return _originalDocId;
	}

	@JSON
	@Override
	public long getFieldId() {
		return _fieldId;
	}

	@Override
	public void setFieldId(long fieldId) {
		_columnBitmask |= FIELDID_COLUMN_BITMASK;

		if (!_setOriginalFieldId) {
			_setOriginalFieldId = true;

			_originalFieldId = _fieldId;
		}

		_fieldId = fieldId;
	}

	public long getOriginalFieldId() {
		return _originalFieldId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public LegalDFRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LegalDFRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LegalDFRelImpl legalDFRelImpl = new LegalDFRelImpl();

		legalDFRelImpl.setDocId(getDocId());
		legalDFRelImpl.setFieldId(getFieldId());

		legalDFRelImpl.resetOriginalValues();

		return legalDFRelImpl;
	}

	@Override
	public int compareTo(LegalDFRel legalDFRel) {
		int value = 0;

		if (getDocId() < legalDFRel.getDocId()) {
			value = -1;
		}
		else if (getDocId() > legalDFRel.getDocId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LegalDFRel)) {
			return false;
		}

		LegalDFRel legalDFRel = (LegalDFRel)obj;

		LegalDFRelPK primaryKey = legalDFRel.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		LegalDFRelModelImpl legalDFRelModelImpl = this;

		legalDFRelModelImpl._originalDocId = legalDFRelModelImpl._docId;

		legalDFRelModelImpl._setOriginalDocId = false;

		legalDFRelModelImpl._originalFieldId = legalDFRelModelImpl._fieldId;

		legalDFRelModelImpl._setOriginalFieldId = false;

		legalDFRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LegalDFRel> toCacheModel() {
		LegalDFRelCacheModel legalDFRelCacheModel = new LegalDFRelCacheModel();

		legalDFRelCacheModel.legalDFRelPK = getPrimaryKey();

		legalDFRelCacheModel.docId = getDocId();

		legalDFRelCacheModel.fieldId = getFieldId();

		return legalDFRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LegalDFRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LegalDFRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDFRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LegalDFRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LegalDFRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LegalDFRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalDFRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LegalDFRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LegalDFRel>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _docId;
	private long _originalDocId;
	private boolean _setOriginalDocId;
	private long _fieldId;
	private long _originalFieldId;
	private boolean _setOriginalFieldId;
	private long _columnBitmask;
	private LegalDFRel _escapedModel;

}