/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecoit.elegaldocument.model.impl;

import com.ecoit.elegaldocument.model.LegalSigner;
import com.ecoit.elegaldocument.model.LegalSignerModel;
import com.ecoit.elegaldocument.model.LegalSignerSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LegalSigner service. Represents a row in the &quot;ecoit_doc_LegalSigner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LegalSignerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LegalSignerImpl}.
 * </p>
 *
 * @author Liverpool
 * @see LegalSignerImpl
 * @generated
 */
@JSON(strict = true)
public class LegalSignerModelImpl
	extends BaseModelImpl<LegalSigner> implements LegalSignerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a legal signer model instance should use the <code>LegalSigner</code> interface instead.
	 */
	public static final String TABLE_NAME = "ecoit_doc_LegalSigner";

	public static final Object[][] TABLE_COLUMNS = {
		{"sigId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createdDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"createdByUser", Types.BIGINT}, {"modifiedByUser", Types.BIGINT},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"language", Types.VARCHAR}, {"statusSigner", Types.BOOLEAN},
		{"fullName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("sigId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdByUser", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedByUser", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusSigner", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("fullName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ecoit_doc_LegalSigner (sigId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,createdByUser LONG,modifiedByUser LONG,firstName VARCHAR(550) null,lastName VARCHAR(550) null,language VARCHAR(75) null,statusSigner BOOLEAN,fullName STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table ecoit_doc_LegalSigner";

	public static final String ORDER_BY_JPQL =
		" ORDER BY legalSigner.createdDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ecoit_doc_LegalSigner.createdDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long LANGUAGE_COLUMN_BITMASK = 4L;

	public static final long SIGID_COLUMN_BITMASK = 8L;

	public static final long STATUSSIGNER_COLUMN_BITMASK = 16L;

	public static final long CREATEDDATE_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LegalSigner toModel(LegalSignerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LegalSigner model = new LegalSignerImpl();

		model.setSigId(soapModel.getSigId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCreatedByUser(soapModel.getCreatedByUser());
		model.setModifiedByUser(soapModel.getModifiedByUser());
		model.setFirstName(soapModel.getFirstName());
		model.setLastName(soapModel.getLastName());
		model.setLanguage(soapModel.getLanguage());
		model.setStatusSigner(soapModel.isStatusSigner());
		model.setFullName(soapModel.getFullName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LegalSigner> toModels(LegalSignerSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LegalSigner> models = new ArrayList<LegalSigner>(
			soapModels.length);

		for (LegalSignerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LegalSignerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sigId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSigId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sigId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LegalSigner.class;
	}

	@Override
	public String getModelClassName() {
		return LegalSigner.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LegalSigner, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LegalSigner, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalSigner, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LegalSigner)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LegalSigner, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LegalSigner, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LegalSigner)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LegalSigner, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LegalSigner, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LegalSigner>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LegalSigner.class.getClassLoader(), LegalSigner.class,
			ModelWrapper.class);

		try {
			Constructor<LegalSigner> constructor =
				(Constructor<LegalSigner>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LegalSigner, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LegalSigner, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LegalSigner, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LegalSigner, Object>>();
		Map<String, BiConsumer<LegalSigner, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LegalSigner, ?>>();

		attributeGetterFunctions.put("sigId", LegalSigner::getSigId);
		attributeSetterBiConsumers.put(
			"sigId", (BiConsumer<LegalSigner, Long>)LegalSigner::setSigId);
		attributeGetterFunctions.put("groupId", LegalSigner::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<LegalSigner, Long>)LegalSigner::setGroupId);
		attributeGetterFunctions.put("companyId", LegalSigner::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LegalSigner, Long>)LegalSigner::setCompanyId);
		attributeGetterFunctions.put("userId", LegalSigner::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<LegalSigner, Long>)LegalSigner::setUserId);
		attributeGetterFunctions.put(
			"createdDate", LegalSigner::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<LegalSigner, Date>)LegalSigner::setCreatedDate);
		attributeGetterFunctions.put(
			"modifiedDate", LegalSigner::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LegalSigner, Date>)LegalSigner::setModifiedDate);
		attributeGetterFunctions.put(
			"createdByUser", LegalSigner::getCreatedByUser);
		attributeSetterBiConsumers.put(
			"createdByUser",
			(BiConsumer<LegalSigner, Long>)LegalSigner::setCreatedByUser);
		attributeGetterFunctions.put(
			"modifiedByUser", LegalSigner::getModifiedByUser);
		attributeSetterBiConsumers.put(
			"modifiedByUser",
			(BiConsumer<LegalSigner, Long>)LegalSigner::setModifiedByUser);
		attributeGetterFunctions.put("firstName", LegalSigner::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName",
			(BiConsumer<LegalSigner, String>)LegalSigner::setFirstName);
		attributeGetterFunctions.put("lastName", LegalSigner::getLastName);
		attributeSetterBiConsumers.put(
			"lastName",
			(BiConsumer<LegalSigner, String>)LegalSigner::setLastName);
		attributeGetterFunctions.put("language", LegalSigner::getLanguage);
		attributeSetterBiConsumers.put(
			"language",
			(BiConsumer<LegalSigner, String>)LegalSigner::setLanguage);
		attributeGetterFunctions.put(
			"statusSigner", LegalSigner::getStatusSigner);
		attributeSetterBiConsumers.put(
			"statusSigner",
			(BiConsumer<LegalSigner, Boolean>)LegalSigner::setStatusSigner);
		attributeGetterFunctions.put("fullName", LegalSigner::getFullName);
		attributeSetterBiConsumers.put(
			"fullName",
			(BiConsumer<LegalSigner, String>)LegalSigner::setFullName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSigId() {
		return _sigId;
	}

	@Override
	public void setSigId(long sigId) {
		_columnBitmask |= SIGID_COLUMN_BITMASK;

		if (!_setOriginalSigId) {
			_setOriginalSigId = true;

			_originalSigId = _sigId;
		}

		_sigId = sigId;
	}

	public long getOriginalSigId() {
		return _originalSigId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedByUser() {
		return _createdByUser;
	}

	@Override
	public void setCreatedByUser(long createdByUser) {
		_createdByUser = createdByUser;
	}

	@JSON
	@Override
	public long getModifiedByUser() {
		return _modifiedByUser;
	}

	@Override
	public void setModifiedByUser(long modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	@JSON
	@Override
	public String getLanguage() {
		if (_language == null) {
			return "";
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		_columnBitmask |= LANGUAGE_COLUMN_BITMASK;

		if (_originalLanguage == null) {
			_originalLanguage = _language;
		}

		_language = language;
	}

	public String getOriginalLanguage() {
		return GetterUtil.getString(_originalLanguage);
	}

	@JSON
	@Override
	public boolean getStatusSigner() {
		return _statusSigner;
	}

	@JSON
	@Override
	public boolean isStatusSigner() {
		return _statusSigner;
	}

	@Override
	public void setStatusSigner(boolean statusSigner) {
		_columnBitmask |= STATUSSIGNER_COLUMN_BITMASK;

		if (!_setOriginalStatusSigner) {
			_setOriginalStatusSigner = true;

			_originalStatusSigner = _statusSigner;
		}

		_statusSigner = statusSigner;
	}

	public boolean getOriginalStatusSigner() {
		return _originalStatusSigner;
	}

	@JSON
	@Override
	public String getFullName() {
		if (_fullName == null) {
			return "";
		}
		else {
			return _fullName;
		}
	}

	@Override
	public void setFullName(String fullName) {
		_fullName = fullName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LegalSigner.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LegalSigner toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LegalSigner>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LegalSignerImpl legalSignerImpl = new LegalSignerImpl();

		legalSignerImpl.setSigId(getSigId());
		legalSignerImpl.setGroupId(getGroupId());
		legalSignerImpl.setCompanyId(getCompanyId());
		legalSignerImpl.setUserId(getUserId());
		legalSignerImpl.setCreatedDate(getCreatedDate());
		legalSignerImpl.setModifiedDate(getModifiedDate());
		legalSignerImpl.setCreatedByUser(getCreatedByUser());
		legalSignerImpl.setModifiedByUser(getModifiedByUser());
		legalSignerImpl.setFirstName(getFirstName());
		legalSignerImpl.setLastName(getLastName());
		legalSignerImpl.setLanguage(getLanguage());
		legalSignerImpl.setStatusSigner(isStatusSigner());
		legalSignerImpl.setFullName(getFullName());

		legalSignerImpl.resetOriginalValues();

		return legalSignerImpl;
	}

	@Override
	public int compareTo(LegalSigner legalSigner) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreatedDate(), legalSigner.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LegalSigner)) {
			return false;
		}

		LegalSigner legalSigner = (LegalSigner)obj;

		long primaryKey = legalSigner.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		LegalSignerModelImpl legalSignerModelImpl = this;

		legalSignerModelImpl._originalSigId = legalSignerModelImpl._sigId;

		legalSignerModelImpl._setOriginalSigId = false;

		legalSignerModelImpl._originalGroupId = legalSignerModelImpl._groupId;

		legalSignerModelImpl._setOriginalGroupId = false;

		legalSignerModelImpl._originalCompanyId =
			legalSignerModelImpl._companyId;

		legalSignerModelImpl._setOriginalCompanyId = false;

		legalSignerModelImpl._originalLanguage = legalSignerModelImpl._language;

		legalSignerModelImpl._originalStatusSigner =
			legalSignerModelImpl._statusSigner;

		legalSignerModelImpl._setOriginalStatusSigner = false;

		legalSignerModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LegalSigner> toCacheModel() {
		LegalSignerCacheModel legalSignerCacheModel =
			new LegalSignerCacheModel();

		legalSignerCacheModel.sigId = getSigId();

		legalSignerCacheModel.groupId = getGroupId();

		legalSignerCacheModel.companyId = getCompanyId();

		legalSignerCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			legalSignerCacheModel.createdDate = createdDate.getTime();
		}
		else {
			legalSignerCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			legalSignerCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			legalSignerCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		legalSignerCacheModel.createdByUser = getCreatedByUser();

		legalSignerCacheModel.modifiedByUser = getModifiedByUser();

		legalSignerCacheModel.firstName = getFirstName();

		String firstName = legalSignerCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			legalSignerCacheModel.firstName = null;
		}

		legalSignerCacheModel.lastName = getLastName();

		String lastName = legalSignerCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			legalSignerCacheModel.lastName = null;
		}

		legalSignerCacheModel.language = getLanguage();

		String language = legalSignerCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			legalSignerCacheModel.language = null;
		}

		legalSignerCacheModel.statusSigner = isStatusSigner();

		legalSignerCacheModel.fullName = getFullName();

		String fullName = legalSignerCacheModel.fullName;

		if ((fullName != null) && (fullName.length() == 0)) {
			legalSignerCacheModel.fullName = null;
		}

		return legalSignerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LegalSigner, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LegalSigner, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalSigner, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LegalSigner)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LegalSigner, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LegalSigner, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LegalSigner, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LegalSigner)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LegalSigner>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _sigId;
	private long _originalSigId;
	private boolean _setOriginalSigId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private Date _createdDate;
	private Date _modifiedDate;
	private long _createdByUser;
	private long _modifiedByUser;
	private String _firstName;
	private String _lastName;
	private String _language;
	private String _originalLanguage;
	private boolean _statusSigner;
	private boolean _originalStatusSigner;
	private boolean _setOriginalStatusSigner;
	private String _fullName;
	private long _columnBitmask;
	private LegalSigner _escapedModel;

}